### ISSUE TITLE
Bumping from 0.33 to 0.34 failing

### ISSUE THREAD

**Issue by pmarsceill** [contentlayerdev/contentlayer#102]
Stack trace:

```
$ next build
--
01:26:56.448 | warn  - SWC minify beta enabled. https://nextjs.org/docs/messages/swc-minify-enabled
01:26:58.505 | This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
01:26:58.505 | https://github.com/contentlayerdev/contentlayer/issues
01:26:58.505 |  
01:26:58.506 | An unchecked error was produced.
01:26:58.506 |  
01:26:58.506 | TypeError: Cannot read property 'cwd' of undefined
01:26:58.506 | at file:///vercel/path0/node_modules/@contentlayer/core/src/cwd.ts:24:53
01:26:58.506 | at /vercel/path0/node_modules/src/Effect/has.ts:121:43
01:26:58.506 | at IRead.f (/vercel/path0/node_modules/src/Effect/has.ts:113:33)
01:26:58.506 | at FiberContext.evaluateNow (/vercel/path0/node_modules/src/Fiber/context.ts:1130:51)
01:26:58.506 | at /vercel/path0/node_modules/src/Fiber/context.ts:571:33
01:26:58.506 | at /vercel/path0/node_modules/src/Support/Scheduler/index.ts:13:23
01:26:58.506 |  
01:26:58.507 | Fiber: #11 (started at: 2022-01-17T06:26:58.460Z) was supposed to continue to:
01:26:58.507 |  
01:26:58.507 | a future continuation at packages/@contentlayer/core/src/ArtifactsDir.ts:29:10
01:26:58.507 | a future continuation at packages/@contentlayer/source-files/src/fetchData/index.ts:45:116
01:26:58.507 |  
01:26:58.507 | Fiber: #11 (started at: 2022-01-17T06:26:58.460Z) Execution trace:
01:26:58.507 |  
01:26:58.507 | packages/@contentlayer/core/src/cwd.ts:24:43
01:26:58.507 | packages/@contentlayer/utils/src/node/version.ts:20:15
01:26:58.507 | packages/@contentlayer/utils/src/node/version.ts:19:10
01:26:58.507 | packages/@contentlayer/utils/src/node/fs.ts:62:17
01:26:58.507 | packages/@contentlayer/utils/src/node/fs.ts:61:12
01:26:58.508 | packages/@contentlayer/utils/src/node/fs.ts:44:22
01:26:58.508 | packages/@contentlayer/core/src/ArtifactsDir.ts:25:13
01:26:58.508 | packages/@contentlayer/core/src/DataCache.ts:46:38
01:26:58.508 | packages/@contentlayer/core/src/DataCache.ts:45:12
01:26:58.508 |  
01:26:58.508 | Fiber: #11 (started at: 2022-01-17T06:26:58.460Z) was spawned by:
01:26:58.508 |  
01:26:58.508 | Fiber: #0 (started at: 2022-01-17T06:26:57.514Z) was supposed to continue to: <empty trace>
01:26:58.508 |  
01:26:58.508 | Fiber: #0 (started at: 2022-01-17T06:26:57.514Z) Execution trace:
01:26:58.508 |  
01:26:58.509 | packages/@contentlayer/core/src/generation/generate-dotpkg.ts:78:13
01:26:58.509 | packages/@contentlayer/core/src/generation/generate-dotpkg.ts:74:16
01:26:58.509 | packages/next-contentlayer/src/plugin.ts:30:12
01:26:58.509 | packages/@contentlayer/core/src/getConfig/index.ts:36:18
01:26:58.509 | packages/@contentlayer/core/src/getConfig/index.ts:35:10
01:26:58.509 | packages/@contentlayer/core/src/getConfig/esbuild.ts:43:15
01:26:58.509 | packages/@contentlayer/core/src/getConfig/esbuild.ts:35:26
01:26:58.509 | packages/@contentlayer/core/src/getConfig/esbuild.ts:33:12
01:26:58.509 | packages/@contentlayer/core/src/getConfig/esbuild.ts:113:12
01:26:58.509 | packages/@contentlayer/core/src/getConfig/esbuild.ts:71:36
01:26:58.509 | packages/@contentlayer/core/src/getConfig/index.ts:163:13
01:26:58.509 | packages/@contentlayer/core/src/getConfig/index.ts:154:26
01:26:58.510 | packages/@contentlayer/core/src/getConfig/index.ts:153:30
01:26:58.510 | packages/@contentlayer/core/src/getConfig/index.ts:143:26
01:26:58.510 | packages/@contentlayer/core/src/getConfig/index.ts:142:31
01:26:58.510 | packages/@contentlayer/core/src/getConfig/index.ts:131:26
01:26:58.510 | packages/@contentlayer/core/src/getConfig/index.ts:130:15
01:26:58.510 | packages/@contentlayer/core/src/getConfig/index.ts:116:10
01:26:58.510 | packages/@contentlayer/core/src/getConfig/esbuild.ts:114:12
01:26:58.510 | packages/@contentlayer/core/src/getConfig/esbuild.ts:117:14
01:26:58.510 | packages/@contentlayer/core/src/getConfig/esbuild.ts:66:15
01:26:58.510 | packages/@contentlayer/core/src/getConfig/esbuild.ts:65:10
01:26:58.510 | packages/@contentlayer/core/src/getConfig/esbuild.ts:64:10
01:26:58.510 | packages/@contentlayer/core/src/getConfig/esbuild.ts:47:22
01:26:58.511 | packages/@contentlayer/core/src/getConfig/esbuild.ts:72:10
01:26:58.511 |  
01:26:58.511 | Fiber: #0 (started at: 2022-01-17T06:26:57.514Z) was spawned by: <empty trace>
01:26:58.511 |  
01:26:58.511 | OS: linux 4.14.252-195.483.amzn2.x86_64 (arch: x64)
01:26:58.511 | Process: /node14/bin/node /vercel/path0/node_modules/.bin/next build
01:26:58.511 | Node version: v14.18.1
01:26:58.511 | Contentlayer version: 0.0.33
01:26:58.511 |  
01:26:58.529 | error Command failed with exit code 1.
01:26:58.529 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
01:26:58.540 | Error: Command "yarn run build" exited with 1
```

v0.33 built with no issues.

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a link to a reproduction repo?

**Comment by pmarsceill** [comment]
👋 sorry for the delay @schickling --- here is the repo (and PR): https://github.com/pmarsceill/this-modern-web/pull/142

**Comment by ichuns** [comment]
@pmarsceill  I have this problem too. It was found that `contentlayer` and `next-contentlayer` were different. I upgraded them to `0.0.34` at the same time, which solved the problem.

I saw dependabot, not upgrading them at the same time: https://github.com/pmarsceill/this-modern-web/blob/89719509c31047d116e9d5fcf0ec44525b22a7a7/package.json#L22

**Comment by schickling** [comment]
As @ichuns mentioned this seems to be a problem with `contentlayer` and `next-contentlayer` not being updated at the same time. Please let me know if you're still running into issues after updating both to the latest & same version.
