### ISSUE TITLE
error - SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by skagur-k** [contentlayerdev/contentlayer#180]
The .mdx.json file generated includes  `"body": { "raw": " ", "html": " "}` .

The expected object to be generated is `"body": { "raw": " ", "code": " "}` , according to the example.

**contentlayer.config.ts**
```ts
export const Blog = defineDocumentType(() => ({
	name: 'Blog',
	filePathPattern: 'blog/*.mdx',
	bodyType: 'mdx',
	fields: {
		title: { type: 'string', required: true},
                publishedAt: { type: 'string', required: true },
	},
	computedFields,
}))

export default makeSource({
	contentDirPath: 'data',
	documentTypes: [Blog],
	mdx: {
		remarkPlugins: [],
		rehypePlugins: [rehypePrism],
	},
})
```

Passing the generated .mdx.json file to `useMDXComponent(source.body.html)` spits out the following error:
```
SyntaxError: Unexpected token '<'
    at new Function (<anonymous>)
    at getMDXComponent (file:///home/skagur/skagur.dev/node_modules/next-contentlayer/src/hooks/useMDXComponent.ts:18:14)
    at file:///home/skagur/skagur.dev/node_modules/next-contentlayer/src/hooks/useMDXComponent.ts:23:30
    at Object.useMemo (/home/skagur/skagur.dev/node_modules/react-dom/cjs/react-dom-server.browser.development.js:4961:19)
    at Object.useMemo (/home/skagur/skagur.dev/node_modules/react/cjs/react.development.js:1645:21)
    at useMDXComponent (file:///home/skagur/skagur.dev/node_modules/next-contentlayer/src/hooks/useMDXComponent.ts:23:16)
    at Post (webpack-internal:///./src/pages/blog/[...slug].js:29:96)
    at renderWithHooks (/home/skagur/skagur.dev/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
    at renderIndeterminateComponent (/home/skagur/skagur.dev/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5521:15)
    at renderElement (/home/skagur/skagur.dev/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5736:7)
```

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by skagur-k** [comment]
> Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

Please refer to the reproduced repo: [REPO](https://github.com/skagur-k/contentlayer-repro)

![image](https://user-images.githubusercontent.com/8953479/163679841-71803566-2fe0-47d2-b083-b28acb4e064f.png)

**Comment by schickling** [comment]
Thanks for the repro and apologies for the inconvenience. Looks like you're missing the `contentType: 'mdx'` option in `defineDocumentType` (which defaults to `markdown`). Once you've set `contentType: 'mdx'` you'll be able to use `useMDXComponent(post.body.code)`.

From docs:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/1567498/163687117-5f6fa221-6a16-4639-8589-6f2e426d58be.png">

Note: I'm also planning to display a warning for situations like these in the future #183

**Comment by HoverBaum** [comment]
Just wanna drop a line that this was super helpful!

I was following a project that used an older version of contentlayer and was confused about how setting `bodyType: 'mdx',` didn't get me the `.code` property. 
But super easily found this issue that helped me solve it 👍
