### ISSUE TITLE
ConfigReadError : compiled contentlayer config not found

### ISSUE THREAD

**Issue by satvik-s** [contentlayerdev/contentlayer#212]
Hi! I am trying to upgrade `contentlayer` and `next-contentlayer` from `0.1` to `0.2` and ran into this issue. The website seems to be building correctly and running but I wanted to see if this error during the build step is expected with the upgrade or not.

Here is the PR: https://github.com/satvik-s/dev-blog-v2/pull/30

Here is the error log from Vercel
```
[18:22:46.469] Installing dependencies...
[18:23:28.347] 
[18:23:28.347] > core-js-pure@3.22.4 postinstall /vercel/path0/node_modules/core-js-pure
[18:23:28.348] > node -e "try{require('./postinstall')}catch(e){}"
[18:23:28.348] 
[18:23:28.424] 
[18:23:28.424] > esbuild@0.14.38 postinstall /vercel/path0/node_modules/esbuild
[18:23:28.424] > node install.js
[18:23:28.424] 
[18:23:28.573] 
[18:23:28.574] > protobufjs@6.11.2 postinstall /vercel/path0/node_modules/protobufjs
[18:23:28.574] > node scripts/postinstall
[18:23:28.574] 
[18:23:28.705] 
[18:23:28.706] > contentlayer@0.2.4 postinstall /vercel/path0/node_modules/contentlayer
[18:23:28.706] > node ./bin/cli.cjs postinstall || echo 'No Contentlayer build found.'
[18:23:28.706] 
[18:23:30.678] ConfigReadError {
[18:23:30.678]   error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/.contentlayer/.cache/v0.2.4/compiled-contentlayer-config-A4IIJG2P.mjs' imported from /vercel/path0/node_modules/@contentlayer/core/dist/getConfig/index.js
[18:23:30.678]       at new NodeError (internal/errors.js:322:7)
[18:23:30.678]       at finalizeResolution (internal/modules/esm/resolve.js:318:11)
[18:23:30.678]       at moduleResolve (internal/modules/esm/resolve.js:776:10)
[18:23:30.678]       at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
[18:23:30.678]       at Loader.resolve (internal/modules/esm/loader.js:89:40)
[18:23:30.679]       at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
[18:23:30.679]       at Loader.import (internal/modules/esm/loader.js:177:28)
[18:23:30.679]       at importModuleDynamically (internal/modules/esm/translators.js:114:35)
[18:23:30.679]       at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
[18:23:30.679]       at importFresh (file:///vercel/path0/node_modules/@contentlayer/core/src/getConfig/index.ts:162:90) {
[18:23:30.679]     code: 'ERR_MODULE_NOT_FOUND'
[18:23:30.679]   },
[18:23:30.679]   configPath: '/vercel/path0/contentlayer.config.ts',
[18:23:30.679]   _tag: 'ConfigReadError',
[18:23:30.679]   toString: [Function (anonymous)],
[18:23:30.679]   [Symbol()]: {
[18:23:30.679]     error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/.contentlayer/.cache/v0.2.4/compiled-contentlayer-config-A4IIJG2P.mjs' imported from /vercel/path0/node_modules/@contentlayer/core/dist/getConfig/index.js
[18:23:30.680]         at new NodeError (internal/errors.js:322:7)
[18:23:30.680]         at finalizeResolution (internal/modules/esm/resolve.js:318:11)
[18:23:30.680]         at moduleResolve (internal/modules/esm/resolve.js:776:10)
[18:23:30.680]         at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
[18:23:30.680]         at Loader.resolve (internal/modules/esm/loader.js:89:40)
[18:23:30.680]         at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
[18:23:30.680]         at Loader.import (internal/modules/esm/loader.js:177:28)
[18:23:30.680]         at importModuleDynamically (internal/modules/esm/translators.js:114:35)
[18:23:30.680]         at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
[18:23:30.680]         at importFresh (file:///vercel/path0/node_modules/@contentlayer/core/src/getConfig/index.ts:162:90) {
[18:23:30.681]       code: 'ERR_MODULE_NOT_FOUND'
[18:23:30.681]     },
[18:23:30.681]     configPath: '/vercel/path0/contentlayer.config.ts'
[18:23:30.681]   },
[18:23:30.681]   [Symbol()]: [ 'configPath', 'error' ]
[18:23:30.681] }
[18:23:30.686] No Contentlayer build found.
```

**Comment by schickling** [comment]
This looks like the same problem as #178. (If not please leave another comment.)
