### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'cwd')

### ISSUE THREAD

**Issue by chopfitzroy** [contentlayerdev/contentlayer#215]
All of a sudden I am seeing the following error (was building fine yesterday):

```
TypeError: Cannot read properties of undefined (reading 'cwd')
```

Have tried:
- Updating content layer (`0.2.4`)
- Updating Next (`12.1.5`)
- Node `16.13`
- Node `16.14`
- Node `17.9`

Cannot get any combination of the above to resolve the issue.

Other things I have tried:
- Nuking the `node_modules/` and `.contentlayer` directory as well.
- Nuking the entire project, re-cloning, re-installing deps.

Full error:
```
TypeError: Cannot read properties of undefined (reading 'cwd')
  at f (file:///website/node_modules/@contentlayer/source-files/node_modules/@contentlayer/core/src/cwd.ts:24:53)
  at f (file:///website/node_modules/@effect-ts/system/_src/Effect/has.ts:121:43)
  at IRead.f (file:///website/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
  at FiberContext.evaluateNow (file:///website/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
  at file:///website/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
  at file:///website/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9

Fiber: #17 (started at: 2022-05-10T06:02:17.445Z) was supposed to continue to:

a future continuation at packages/@contentlayer/core/src/ArtifactsDir.ts:29:10
a future continuation at packages/@contentlayer/source-files/src/fetchData/index.ts:54:116

Fiber: #17 (started at: 2022-05-10T06:02:17.445Z) Execution trace:

packages/@contentlayer/core/src/cwd.ts:24:43
packages/@contentlayer/utils/src/node/version.ts:21:15
packages/@contentlayer/utils/src/node/version.ts:20:10
packages/@contentlayer/utils/src/node/fs.ts:62:17
packages/@contentlayer/utils/src/node/fs.ts:61:12
packages/@contentlayer/utils/src/node/fs.ts:44:22
packages/@contentlayer/core/src/ArtifactsDir.ts:25:13
packages/@contentlayer/core/src/DataCache.ts:46:38
packages/@contentlayer/core/src/DataCache.ts:45:12
```

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by chopfitzroy** [comment]
Welp! It was `next-contentlayer` version! I am so sorry!

Closing this issue out now, will re-open if I see it again. Thanks again!

**Comment by schickling** [comment]
Related: #187

**Comment by graygalaxy** [comment]
I am getting a similar error. But the error only occurs on the `build` command.

Also interestingly enough this error **does not** always happen in the **same file** or path. 😒

### Relevant log output
```
info  - Collecting page data
[    ] info  - Generating static pages (0/15)TypeError: Cannot read properties of undefined (reading 'code')
       at Articles (PATH_TO_PROJECT\.next\server\pages\[slug].js:37:107)
```

**Comment by schickling** [comment]
@graygalaxy if you're still facing this issue, please open a new issue with a reproduction repository and link to this issue. Thanks!
