### ISSUE TITLE
'process is not defined' error when importing components that include Next.js Link in MDX files

### ISSUE THREAD

**Issue by olayway** [contentlayerdev/contentlayer#288]
## Bug description
Importing React components that include Next.js's `Link` into MDX files results in the following client-side error:

![image](https://user-images.githubusercontent.com/52197250/184024132-8b96b89a-85c2-43f3-95fd-0a7980252192.png)

## Reproduction steps

1. Clone this repo: https://github.com/olayway/next-contentlayer-example (`nextjs-links` branch)
(It's a copy of your original next-contentlayer-example repo, just with small changes)
2. Go to `posts/click-me.md` and uncomment the last two lines.
3. Run `npm install && npm run dev`
4. Click on the post named `Click me!` to go the page with the imported Button component . 🐛

## May be helpful
It seems the problem is related to the code that is produced by esbuild for the page that imports such components. It includes a lot of references to the `process` variable which of course will be undefined outside of Node.

This is a part of the json file generated by contentlayer for such a page:

```json

"code": "[...] var En=process.env.__NEXT_TRAILING_SLASH?e=>/\\.[^/]+\\/?$/.test(e)?Be(e):e.endsWith(\"/\")?e:e+\"/\":Be;le.normalizePathTrailingSlash=En}) [...]"

```

Not sure if relevant, but someone has a similar problem when using [mdx-bundler](https://github.com/kentcdodds/mdx-bundler) - see [this issue](https://github.com/kentcdodds/mdx-bundler/issues/165).

## Logs
```
VM609:3 Uncaught ReferenceError: process is not defined
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:3:992)
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:3:269)
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:6:29295)
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:3:269)
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:10:1818)
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:3:269)
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:12:1115)
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:3:269)
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:12:1201)
    at eval (eval at getMDXComponent (useMDXComponent.js:1:1), <anonymous>:12:1573)
    at getMDXComponent (useMDXComponent.js?ae92:18:1)
    at eval (useMDXComponent.js?ae92:21:25)
    at mountMemo (react-dom.development.js?ac89:15846:1)
    at Object.useMemo (react-dom.development.js?ac89:16219:1)
    at Object.useMemo (react.development.js?1b7e:1532:1)
    at useMDXComponent (useMDXComponent.js?ae92:21:12)
    at Page ([[...slug]].js?655a:12:36)
    at renderWithHooks (react-dom.development.js?ac89:14985:1)
    at mountIndeterminateComponent (react-dom.development.js?ac89:17811:1)
    at beginWork (react-dom.development.js?ac89:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at beginWork$1 (react-dom.development.js?ac89:23964:1)
    at performUnitOfWork (react-dom.development.js?ac89:22776:1)
    at workLoopSync (react-dom.development.js?ac89:22707:1)
    at renderRootSync (react-dom.development.js?ac89:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js?ac89:22293:1)
    at scheduleUpdateOnFiber (react-dom.development.js?ac89:21881:1)
    at updateContainer (react-dom.development.js?ac89:25482:1)
    at eval (react-dom.development.js?ac89:26021:1)
    at unbatchedUpdates (react-dom.development.js?ac89:22431:1)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js?ac89:26020:1)
    at Object.hydrate (react-dom.development.js?ac89:26086:1)
    at renderReactElement (index.js?46cb:515:31)
    at doRender (index.js?46cb:831:5)
    at _callee$ (index.js?46cb:408:19)
    at tryCatch (runtime.js?ecd4:45:16)
    at Generator.invoke [as _invoke] (runtime.js?ecd4:274:1)
    at prototype.<computed> [as next] (runtime.js?ecd4:97:1)
    at asyncGeneratorStep (index.js?46cb:30:27)
    at _next (index.js?46cb:48:17)
    at eval (index.js?46cb:53:13)
    at new Promise (<anonymous>)
    at eval (index.js?46cb:45:16)
    at _render (index.js?46cb:427:20)
    at render (index.js?46cb:430:20)
    at _callee$ (index.js?46cb:394:9)
    at tryCatch (runtime.js?ecd4:45:16)
    at Generator.invoke [as _invoke] (runtime.js?ecd4:274:1)

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a **minimal** reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by olayway** [comment]
Sure. I've updated an original comment with the repo and instructions. And thank you for such a quick reply 🌷!

**Comment by schickling** [comment]
Sorry for the late reply and thanks for your comment. I've just taken a look at the linked reproduction repository. However it seems to be rather big and thus makes it much more time intensive for me to investigate. It would be great if you could create a new repository with a **minimal** reproduction of the problem (i.e. minimal amount of files/code/config etc).

**Comment by olayway** [comment]
Hello @schickling. Here is a minimal reproduction repo - https://github.com/olayway/minimal-flowershow. There is only one content file: `content/index.md`. When you clone the repo, do `npm install && npm run dev` and uncomment the import statement, you should see the error described in the issue above.

**Comment by john-tipper** [comment]
I'm having a similar issue, have you managed to find a workaround please?

**Comment by schickling** [comment]
@olayway thanks for circling back on this but please try to reduce the repro you've provided to the **absolute minimum** (e.g. remove all config files, components, etc that are not necessary to demonstrate the problem you're facing). It takes me considerably longer to investigate non-minimal repros and thus unfortunately will lead to me de-prioritizing this work.

@john-tipper if you could provide a **minimal repro** as well, that could be helpful :)

**Comment by olayway** [comment]
@schickling here is the minimal repo: https://github.com/olayway/next-contentlayer-example/tree/nextjs-links

**Comment by olayway** [comment]
@schickling It works! Thank you so much! 💛
