### ISSUE TITLE
Error: Cannot find module '@opentelemetry/sdk-trace-base'

### ISSUE THREAD

**Issue by kicut** [contentlayerdev/contentlayer#30]
I installed next js typescript with next-content layer. when running `yarn dev` command, it returns error.

Repo: https://github.com/kicut/learn-nextjs-contentlayer

Error in Terminal:

```
➜  learn-nextjs-contentlayer git:(main) yarn dev 
yarn run v1.22.17
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - SWC minify beta enabled. https://nextjs.org/docs/messages/swc-minify-enabled
Error: Cannot find module '@opentelemetry/sdk-trace-base'
Require stack:
- /home/kicut/code/project/next-contentlayer/node_modules/@effect-ts/otel/Processor/Simple/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/home/kicut/code/project/next-contentlayer/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/kicut/code/project/next-contentlayer/node_modules/@effect-ts/otel/Processor/Simple/index.js:52:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kicut/code/project/next-contentlayer/node_modules/@effect-ts/otel/Processor/Simple/index.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jahirfiquitiva** [comment]
I'm facing the very same issue 😕😭

Why is that package needed? How can we remove it entirely?

**Comment by schickling** [comment]
Sorry for the inconvenience. I'm looking into the issue.

**Comment by schickling** [comment]
This should be fixed on the newest `@dev` version. Would be great if you could give it a try via `yarn add contentlayer@dev next-contentlayer@dev` and report back here whether this issue was solved for you.

**Comment by kicut** [comment]
@schickling yes now working fine, when is this released?

**Comment by schickling** [comment]
There we go: 🚀 

https://github.com/contentlayerdev/contentlayer/releases/tag/v0.0.29
