### ISSUE TITLE
An unchecked error was produced

### ISSUE THREAD

**Issue by nmktad** [contentlayerdev/contentlayer#301]
the error shows this message and below is the stack trace
- the error occured after I made some changes to mdx blog file

```
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues
An unchecked error was produced.

TypeError: Cannot read properties of null (reading 'title')
    at mapValue (file:///C:/Users/nmkta/Projects/portfolio/node_modules/@contentlayer/source-files/src/fetchData/mapping.ts:125:40)
    at f (file:///C:/Users/nmkta/Projects/portfolio/node_modules/@contentlayer/utils/src/effect/Effect.ts:66:44)
    at f (file:///C:/Users/nmkta/Projects/portfolio/node_modules/@effect-ts/system/_src/Effect/excl-forEach.ts:77:18)
    at forEachUnitLoop (file:///C:/Users/nmkta/Projects/portfolio/node_modules/@effect-ts/system/_src/Effect/excl-forEach.ts:146:19)
    at ISuspend.factory (file:///C:/Users/nmkta/Projects/portfolio/node_modules/@effect-ts/system/_src/Effect/excl-forEach.ts:161:29)
    at FiberContext.evaluateNow (file:///C:/Users/nmkta/Projects/portfolio/node_modules/@effect-ts/system/_src/Fiber/context.ts:1173:51)
    at file:///C:/Users/nmkta/Projects/portfolio/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
    at file:///C:/Users/nmkta/Projects/portfolio/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9

Fiber: #293 (started at: 2022-09-07T08:38:09.891Z) was supposed to continue to: <empty trace>

Fiber: #293 (started at: 2022-09-07T08:38:09.891Z) Execution trace:

  packages/@contentlayer/source-files/src/fetchData/mapping.ts:120:31
  packages/@contentlayer/source-files/src/fetchData/mapping.ts:119:8

Fiber: #293 (started at: 2022-09-07T08:38:09.891Z) was spawned by:

Fiber: #287 (started at: 2022-09-07T08:38:09.888Z) was supposed to continue to: <empty trace>

Fiber: #287 (started at: 2022-09-07T08:38:09.888Z) Execution trace:

  packages/@contentlayer/source-files/src/fetchData/mapping.ts:235:24
  packages/@contentlayer/source-files/src/fetchData/mapping.ts:234:24
  packages/@contentlayer/source-files/src/fetchData/mapping.ts:159:8

Fiber: #287 (started at: 2022-09-07T08:38:09.888Z) was spawned by:

Fiber: #28 (started at: 2022-09-07T07:26:56.322Z) was supposed to continue to:

  a future continuation at packages/@contentlayer/source-files/src/fetchData/mapping.ts:75:15

Fiber: #28 (started at: 2022-09-07T07:26:56.322Z) Execution trace:

  packages/@contentlayer/source-files/src/fetchData/mapping.ts:48:33
  packages/@contentlayer/source-files/src/fetchData/mapping.ts:37:10
  packages/@contentlayer/source-files/src/fetchData/DocumentContext.ts:21:96
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:82:32
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:78:16
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:77:18
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:233:19
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:196:8
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:116:42
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:233:19
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:196:8
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:116:42
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:233:19
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:196:8
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:116:42
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:233:19
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:196:8
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:116:42
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:233:19
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:196:8
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:116:42
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:233:19
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:196:8
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:116:42
  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:74:15

Fiber: #28 (started at: 2022-09-07T07:26:56.322Z) was spawned by:

Fiber: #24 (started at: 2022-09-07T07:26:56.321Z) was supposed to continue to: <empty trace>

Fiber: #24 (started at: 2022-09-07T07:26:56.321Z) Execution trace: <empty trace>

Fiber: #24 (started at: 2022-09-07T07:26:56.321Z) was spawned by:

Fiber: #23 (started at: 2022-09-07T07:26:56.320Z) was supposed to continue to: <empty trace>

Fiber: #23 (started at: 2022-09-07T07:26:56.320Z) Execution trace: <empty trace>

Fiber: #23 (started at: 2022-09-07T07:26:56.320Z) was spawned by:

Fiber: #22 (started at: 2022-09-07T07:26:56.210Z) was supposed to continue to: <empty trace>

Fiber: #22 (started at: 2022-09-07T07:26:56.210Z) Execution trace:

  packages/@contentlayer/source-files/src/fetchData/index.ts:54:116
  packages/@contentlayer/utils/src/node/fs.ts:75:15
  packages/@contentlayer/utils/src/node/fs.ts:62:17
  packages/@contentlayer/utils/src/node/fs.ts:61:12
  packages/@contentlayer/utils/src/node/fs.ts:44:22
  packages/@contentlayer/utils/src/node/fs.ts:74:12
  packages/@contentlayer/utils/src/node/fs.ts:16:10
  packages/@contentlayer/utils/src/node/fs.ts:15:15
  packages/@contentlayer/utils/src/node/fs.ts:14:10
  packages/@contentlayer/utils/src/node/fs.ts:30:27
  packages/@contentlayer/core/src/DataCache.ts:50:31
  packages/@contentlayer/core/src/DataCache.ts:49:17
  packages/@contentlayer/core/src/ArtifactsDir.ts:30:10
  packages/@contentlayer/core/src/cwd.ts:24:43
  packages/@contentlayer/utils/src/node/version.ts:21:15
  packages/@contentlayer/utils/src/node/version.ts:20:10
  packages/@contentlayer/utils/src/node/fs.ts:62:17
  packages/@contentlayer/utils/src/node/fs.ts:61:12
  packages/@contentlayer/utils/src/node/fs.ts:44:22
  packages/@contentlayer/core/src/ArtifactsDir.ts:26:13
  packages/@contentlayer/core/src/DataCache.ts:46:38
  packages/@contentlayer/core/src/DataCache.ts:45:12

Fiber: #22 (started at: 2022-09-07T07:26:56.210Z) was spawned by:

Fiber: #17 (started at: 2022-09-07T07:26:56.126Z) was supposed to continue to: <empty trace>

Fiber: #17 (started at: 2022-09-07T07:26:56.126Z) Execution trace:

  packages/@contentlayer/core/src/generation/generate-dotpkg.ts:82:13
  packages/@contentlayer/core/src/generation/generate-dotpkg.ts:78:16

Fiber: #17 (started at: 2022-09-07T07:26:56.126Z) was spawned by:

Fiber: #15 (started at: 2022-09-07T07:26:56.123Z) was supposed to continue to: <empty trace>

Fiber: #15 (started at: 2022-09-07T07:26:56.123Z) Execution trace: <empty trace>

Fiber: #15 (started at: 2022-09-07T07:26:56.123Z) was spawned by:

Fiber: #11 (started at: 2022-09-07T07:26:56.119Z) was supposed to continue to: <empty trace>

Fiber: #11 (started at: 2022-09-07T07:26:56.119Z) Execution trace: <empty trace>

Fiber: #11 (started at: 2022-09-07T07:26:56.119Z) was spawned by:

Fiber: #3 (started at: 2022-09-07T07:26:35.476Z) was supposed to continue to: <empty trace>

Fiber: #3 (started at: 2022-09-07T07:26:35.476Z) Execution trace:

  packages/next-contentlayer/src/plugin.ts:21:94
  packages/@contentlayer/utils/src/effect/Stream.ts:32:83
  packages/@contentlayer/core/src/getConfig/index.ts:197:13
  packages/@contentlayer/core/src/getConfig/index.ts:186:28
  packages/@contentlayer/core/src/getConfig/index.ts:184:44
  packages/@contentlayer/core/src/getConfig/index.ts:171:28
  packages/@contentlayer/core/src/getConfig/index.ts:169:31
  packages/@contentlayer/core/src/getConfig/index.ts:156:28
  packages/@contentlayer/core/src/getConfig/index.ts:154:15
  packages/@contentlayer/core/src/getConfig/index.ts:151:15
  packages/@contentlayer/core/src/getConfig/index.ts:150:15
  packages/@contentlayer/core/src/cwd.ts:24:43
  packages/@contentlayer/core/src/getConfig/index.ts:135:27
  packages/@contentlayer/core/src/getConfig/index.ts:122:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:118:12
  packages/@contentlayer/core/src/getConfig/esbuild.ts:121:14
  packages/@contentlayer/core/src/getConfig/esbuild.ts:70:15
  packages/@contentlayer/core/src/getConfig/esbuild.ts:69:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:68:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:51:22
  packages/@contentlayer/core/src/getConfig/esbuild.ts:76:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:75:12
  packages/@contentlayer/core/src/getConfig/esbuild.ts:75:46
  packages/@contentlayer/core/src/getConfig/esbuild.ts:89:20
  packages/@contentlayer/core/src/getConfig/esbuild.ts:88:12

Fiber: #3 (started at: 2022-09-07T07:26:35.476Z) was spawned by:

Fiber: #0 (started at: 2022-09-07T07:26:35.456Z) was supposed to continue to: <empty trace>

Fiber: #0 (started at: 2022-09-07T07:26:35.456Z) Execution trace:

  packages/@contentlayer/utils/src/tracing-effect/index.ts:45:45
  packages/@contentlayer/core/src/cwd.ts:22:49
  packages/@contentlayer/core/src/cwd.ts:9:18
  packages/@contentlayer/core/src/cwd.ts:8:23
  packages/@contentlayer/core/src/cwd.ts:7:29
  packages/@contentlayer/core/src/runMain.ts:23:32
  packages/@contentlayer/utils/src/effect/ConsoleService.ts:9:18
  packages/@contentlayer/core/src/runMain.ts:16:19
  packages/@contentlayer/core/src/runMain.ts:14:12

Fiber: #0 (started at: 2022-09-07T07:26:35.456Z) was spawned by: <empty trace>

OS: win32 10.0.19044 (arch: x64)
Process: C:\Program Files\nodejs\node.exe C:\Users\nmkta\Projects\portfolio\node_modules\next\dist\bin\next dev
Node version: v16.17.0
Contentlayer version: 0.2.6
```

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!
