### ISSUE TITLE
Can't upgrade to 0.0.28 successfully

### ISSUE THREAD

**Issue by imadatyatalah** [contentlayerdev/contentlayer#31]
I Can't upgrade to 0.0.28 successfully, And I'm getting this weird error(locally & vercel):

```bash
22:32:38.406 | This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
-- | --
22:32:38.406 | https://github.com/contentlayerdev/contentlayer/issues
22:32:38.407 |  
22:32:38.407 | An unchecked error was produced.
22:32:38.407 |  
22:32:38.407 | TypeError: Cannot read property 'get' of undefined
22:32:38.408 | at ApplyFrame.apply  (/vercel/path0/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Layer/definitions.js:391:60)
22:32:38.408 | at FiberContext.nextInstr  (/vercel/path0/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Fiber/context.js:315:22)
22:32:38.408 | at FiberContext.evaluateNow  (/vercel/path0/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Fiber/context.js:699:56)
22:32:38.408 | at /vercel/path0/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Fiber/context.js:458:54
22:32:38.408 | at /vercel/path0/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Support/Scheduler/index.js:34:30
22:32:38.408 |  
22:32:38.408 | Fiber: #2 (started at: 2021-11-08T21:32:38.391Z) was supposed to continue to: <empty trace>
22:32:38.408 |  
22:32:38.410 | Fiber: #2 (started at: 2021-11-08T21:32:38.391Z) Execution trace: <empty trace>
22:32:38.410 |  
22:32:38.410 | Fiber: #2 (started at: 2021-11-08T21:32:38.391Z) was spawned by:
22:32:38.410 |  
22:32:38.410 | Fiber: #0 (started at: 2021-11-08T21:32:38.383Z) was supposed to continue to:
22:32:38.410 |  
22:32:38.411 | a future continuation at packages/@contentlayer/core/src/runMain.ts:15:110
22:32:38.411 |  
22:32:38.411 | Fiber: #0 (started at: 2021-11-08T21:32:38.383Z) Execution trace:
22:32:38.411 |  
22:32:38.411 | packages/@contentlayer/core/src/runMain.ts:15:32
22:32:38.411 | packages/@contentlayer/core/src/runMain.ts:10:12
22:32:38.411 |  
22:32:38.411 | Fiber: #0 (started at: 2021-11-08T21:32:38.383Z) was spawned by: <empty trace>
```

**Comment by schickling** [comment]
Thanks for opening this issue. @imadatyatalah can you please provide more information? When does this error occur?

**Comment by imadatyatalah** [comment]
The error occurs when I run `npm run dev`(using linux Pop OS) or when deploy to vercel.
