### ISSUE TITLE
Using remark-shiki-twoslash as a remarkPlugin causes exception

### ISSUE THREAD

**Issue by c-kirkeby** [contentlayerdev/contentlayer#326]
Trying to add some syntax highlighting after trying out contentlayer, and I got Highlight working, but I wanted to try to integrate shiki-twoslash since the contentlayer documentation states that you can pass it remark plugins. I took the example on this repo with Next.js and I modified it to use MDX as per documentation, and I've got a reproducible example below:

https://gitpod.io/#snapshot/00ba9478-a693-4bf6-8729-30b474363955

Here's the full error:
```
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
✘ [ERROR] [plugin @mdx-js/esbuild] TypeError: attacher.call is not a function
    at Function.freeze (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:136:36)
    at Function.process (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:375:15)
    at process (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:46:22)
    at onload (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/esbuild/lib/index.js:149:22)
    at callback (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:993:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at handleRequest (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:721:30)

    _mdx_bundler_entry_point-549c2ad7-b0c9-4e5e-95a9-59b00022ef2f.mdx:0:0:
      0 │ ---
        ╵ ^

✘ [ERROR] [plugin @mdx-js/esbuild] TypeError: attacher.call is not a function
    at Function.freeze (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:136:36)
    at Function.process (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:375:15)
    at process (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:46:22)
    at onload (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/esbuild/lib/index.js:149:22)
    at callback (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:993:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at handleRequest (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:721:30)

    _mdx_bundler_entry_point-09702be5-fb77-405d-bff9-33cb167a8f18.mdx:0:0:
      0 │ ---
        ╵ ^

✘ [ERROR] [plugin @mdx-js/esbuild] TypeError: attacher.call is not a function
    at Function.freeze (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:136:36)
    at Function.process (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:375:15)
    at process (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:46:22)
    at onload (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/esbuild/lib/index.js:149:22)
    at callback (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:993:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at handleRequest (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:721:30)

    _mdx_bundler_entry_point-c884ca7b-52a6-4413-8ced-7673e8b6dd3e.mdx:0:0:
      0 │ ---
        ╵ ^

Error: Found 3 problems in 3 documents.

 └── Encountered unexpected errors while processing of 3 documents. This is possibly a bug in Contentlayer. Please open an issue.
     
     • "change-me.mdx": UnexpectedMDXError: Error: Build failed with 1 error:
     _mdx_bundler_entry_point-c884ca7b-52a6-4413-8ced-7673e8b6dd3e.mdx:0:0: ERROR: [plugin: @mdx-js/esbuild] TypeError: attacher.call is not a function
         at Function.freeze (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:136:36)
         at Function.process (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:375:15)
         at process (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:46:22)
         at onload (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/esbuild/lib/index.js:149:22)
         at callback (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:993:34)
         at processTicksAndRejections (node:internal/process/task_queues:96:5)
         at handleRequest (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:721:30)
     • "click-me.mdx": UnexpectedMDXError: Error: Build failed with 1 error:
     _mdx_bundler_entry_point-549c2ad7-b0c9-4e5e-95a9-59b00022ef2f.mdx:0:0: ERROR: [plugin: @mdx-js/esbuild] TypeError: attacher.call is not a function
         at Function.freeze (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:136:36)
         at Function.process (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:375:15)
         at process (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:46:22)
         at onload (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/esbuild/lib/index.js:149:22)
         at callback (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:993:34)
         at processTicksAndRejections (node:internal/process/task_queues:96:5)
         at handleRequest (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:721:30)
     • "what-is-contentlayer.mdx": UnexpectedMDXError: Error: Build failed with 1 error:
     _mdx_bundler_entry_point-09702be5-fb77-405d-bff9-33cb167a8f18.mdx:0:0: ERROR: [plugin: @mdx-js/esbuild] TypeError: attacher.call is not a function
         at Function.freeze (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:136:36)
         at Function.process (file:///workspace/next-contentlayer-example/node_modules/unified/lib/index.js:375:15)
         at process (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:46:22)
         at onload (file:///workspace/next-contentlayer-example/node_modules/@mdx-js/esbuild/lib/index.js:149:22)
         at callback (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:993:34)
         at processTicksAndRejections (node:internal/process/task_queues:96:5)
         at handleRequest (/workspace/next-contentlayer-example/node_modules/esbuild/lib/main.js:721:30)
     

SourceFetchDataError: {
  "_tag": "HandledFetchDataError"
}
```

I suspect this is probably an issue with `shiki-twoslash` but I wanted to raise it in case it's something on the contentlayer end.

**Comment by schickling** [comment]
Thanks a lot for creating this issue. Having used `shiki-twoslash` myself (and in fact - we're using it for the Contentlayer website as well) I can say that using `shiki-twoslash` can be a bit tricky. I'm pretty sure it's probably a problem of using `shiki-twoslash` than a problem in Contentlayer.

In any case this needs further investigation that shows this is a problem with Contentlayer. Once this is more clear, I'm happy to take a closer look.

**Comment by schickling** [comment]
@c-kirkeby could you try the following? As [mentioned here](https://github.com/shikijs/twoslash/issues/147#issuecomment-1076816797) add an extra `.default`.

```ts
import remarkShikiTwoslash from 'remark-shiki-twoslash'

// ...

export default makeSource({
  contentDirPath: 'content',
  documentTypes: [Post],
  markdown: {
    remarkPlugins: [[remarkShikiTwoslash.default, { theme: 'dark-plus' }]],
  },
})
```

**Comment by joshferrell** [comment]
@schickling Does this still work for you in the current versions? I now get: 

```
✘ [ERROR] Error: Cannot compile `mdxjsEsm` node
    at unknown (file:///workspace/node_modules/.pnpm/hast-util-raw@7.2.3/node_modules/hast-util-raw/lib/index.js:511:9)
    at one (file:///workspace/node_modules/.pnpm/zwitch@2.0.4/node_modules/zwitch/index.js:108:17)
    at all (file:///workspace/node_modules/.pnpm/hast-util-raw@7.2.3/node_modules/hast-util-raw/lib/index.js:254:13)
    at root (file:///workspace/node_modules/.pnpm/hast-util-raw@7.2.3/node_modules/hast-util-raw/lib/index.js:264:9)
    at one (file:///workspace/node_modules/.pnpm/zwitch@2.0.4/node_modules/zwitch/index.js:108:17)
    at fragment (file:///workspace/node_modules/.pnpm/hast-util-raw@7.2.3/node_modules/hast-util-raw/lib/index.js:213:9)
    at raw (file:///workspace/node_modules/.pnpm/hast-util-raw@7.2.3/node_modules/hast-util-raw/lib/index.js:150:43)
    at file:///workspace/node_modules/.pnpm/rehype-raw@6.1.1/node_modules/rehype-raw/index.js:18:41
    at wrapped (file:///workspace/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:115:27)
    at next (file:///workspace/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:65:23)
    at done (file:///workspace/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:148:7)
    at then (file:///workspace/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:158:5)
    at wrapped (file:///workspace/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:136:9)
    at next (file:///workspace/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:65:23)
    at done (file:///workspace/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:148:7)
    at then (file:///workspace/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:158:5) [plugin @mdx-js/esbuild]

    _mdx_bundler_entry_point-d4fb8ae6-7c99-4996-823c-86cc6c3e25cf.mdx:0:0:
      0 │ ---
        ╵ ^
```

I don't know if it's actually failing at the shiki plugin as I get a different error when I don't include rehypeRaw. 

[Here's a branch that's broken at the moment](https://github.com/joshferrell/website/tree/broken-shiki)

**Comment by nkilm** [comment]
@c-kirkeby Not related to the issue but you can try using [rehype-pretty-code](https://rehype-pretty-code.netlify.app/), which makes use of [build-time](https://rehype-pretty-code.netlify.app/#:~:text=There%27s%20no%20runtime%20or%20bundle%20size%20cost) syntax highlighting. Also It is very simple to use.

You can checkout this PR - https://github.com/umami-software/website/pull/111

**Comment by joshferrell** [comment]
> @c-kirkeby Not related to the issue but you can try using [rehype-pretty-code](https://rehype-pretty-code.netlify.app/), which makes use of [build-time](https://rehype-pretty-code.netlify.app/#:~:text=There%27s%20no%20runtime%20or%20bundle%20size%20cost) syntax highlighting. Also It is very simple to use.
> 
> You can checkout this PR - https://github.com/umami-software/website/pull/111

Yeah, the rest of shiki plugins work fine, but you miss out on the ability to annotate type errors in the markdown. It's really useful when writing a blog post about the pros of typescript.

**Comment by nkilm** [comment]
@joshferrell Oh, I had no idea about that. Thanks for letting me know!

**Comment by joshferrell** [comment]
I've resolved this issue on my end now by adding the following to the contentlayer config:

```js
import { makeSource } from 'contentlayer/source-files';
import rehypeRaw from 'rehype-raw';
import { nodeTypes } from '@mdx-js/mdx';
import remarkShikiTwoslash from 'remark-shiki-twoslash';

export default makeSource({
  documentTypes: [Post],
  mdx: {
    remarkPlugins: [[remarkShikiTwoslash.default, { theme: 'dark-plus' }]],
    rehypePlugins: [[rehypeRaw, { passThrough: nodeTypes }]],
  }
});
```
