### ISSUE TITLE
SyntaxError: Unexpected token '<' when using Contentlayer, Next and TS with MDX components

### ISSUE THREAD

**Issue by olayway** [contentlayerdev/contentlayer#334]
## What happens
When using Contentlayer with Next.js and TS, importing components in MDX files fails with the following error:

```sh
error - SyntaxError: Unexpected token '<'
    at new Function (<anonymous>)
    at getMDXComponent (file:///home/ola/Projects/next-contentlayer-example/node_modules/next-contentlayer/src/hooks/useMDXComponent.ts:18:14)
    at file:///home/ola/Projects/next-contentlayer-example/node_modules/next-contentlayer/src/hooks/useMDXComponent.ts:23:30
    at Object.useMemo (/home/ola/Projects/next-contentlayer-example/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
    at Object.useMemo (/home/ola/Projects/next-contentlayer-example/node_modules/react/cjs/react.development.js:1650:21)
    at useMDXComponent (file:///home/ola/Projects/next-contentlayer-example/node_modules/next-contentlayer/src/hooks/useMDXComponent.ts:23:16)
    at PostLayout (webpack-internal:///./pages/posts/[slug].tsx:39:98)
    at renderWithHooks (/home/ola/Projects/next-contentlayer-example/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/ola/Projects/next-contentlayer-example/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/home/ola/Projects/next-contentlayer-example/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7) {
  page: '/posts/[slug]'
}
```

## Reproduction steps
1. Clone this repo: https://github.com/olayway/next-contentlayer-example (main branch)
(It's a copy of your original next-contentlayer-example repo, just with small changes)
2. Go to `posts/click-me.md` and uncomment the last two lines.
3. Run `npm install && npm run dev` 🐛

## Notes
I think the source of the problem is the `jsx` field in the `tsconfig.json` file wich is being added/overridden by Next to be set as `jsx: preserve`, whereas the default value is `jsx: react`. I've tested it by only running `contentlayer build` (so that Next js doesn't override the `tsconfig.json`) with two different values of `jsx` field, and checked the output in `click-me.json`:

### With `jsx: react`

```json
  "title": "Click me!",
  "date": "2022-02-28T00:00:00.000Z",
  "body": {
    "raw": "\nBlog posts have their own pages. The content source is a markdown file, parsed to HTML by Contentlayer.\n\n\nimport { Button } from \"components/Button.tsx\"\n\n<Button title=\"test\"/>\n",
    "code": "var Component=(()=>{var j=Object.create;var s=Object.defineProperty;var _=Object.getOwnPropertyDescriptor;var b=Object.getOwnPropertyNames;var h=Object.getPrototypeOf,C=Object.prototype.hasOwnProperty;var a=(t,e)=>()=>(e||t((e={exports:{}}).exports,e),e.exports),k=(t,e)=>{for(var o in e)s(t,o,{get:e[o],enumerable:!0})},c=(t,e,o,i)=>{if(e&&typeof e==\"object\"||typeof e==\"function\")for(let r of b(e))!C.call(t,r)&&r!==o&&s(t,r,{get:()=>e[r],enumerable:!(i=_(e,r))||i.enumerable});return t};var l=(t,e,o)=>(o=t!=null?j(h(t)):{},c(e||!t||!t.__esModule?s(o,\"default\",{value:t,enumerable:!0}):o,t)),y=t=>c(s({},\"__esModule\",{value:!0}),t);var m=a((F,d)=>{d.exports=_jsx_runtime});var u=a((H,p)=>{p.exports=React});var B={};k(B,{default:()=>v,frontmatter:()=>w});var n=l(m());var f=l(u());function x(t){return f.default.createElement(\"div\",{style:{padding:10,backgroundColor:\"#333\",color:\"#fff\",display:\"inline-block\",borderRadius:4},onClick:function(){return alert(\"Hi\")}},t.title)}var w={title:\"Click me!\",date:new Date(16460064e5)};function g(t){let e=Object.assign({p:\"p\"},t.components);return(0,n.jsxs)(n.Fragment,{children:[(0,n.jsx)(e.p,{children:\"Blog posts have their own pages. The content source is a markdown file, parsed to HTML by Contentlayer.\"}),`\n`,`\n`,(0,n.jsx)(x,{title:\"test\"})]})}function M(t={}){let{wrapper:e}=t.components||{};return e?(0,n.jsx)(e,Object.assign({},t,{children:(0,n.jsx)(g,t)})):g(t)}var v=M;return y(B);})();\n;return Component;"
  },
  ...
}
```

JSX is correctly converted to JS, you can see `createElement` function calls in `body.code` field:
```
function x(t){return f.default.createElement(\"div\",{style: ...
```

### With `jsx: preserve`

```json
{
  "title": "Click me!",
  "date": "2022-02-28T00:00:00.000Z",
  "body": {
    "raw": "\nBlog posts have their own pages. The content source is a markdown file, parsed to HTML by Contentlayer.\n\n\nimport { Button } from \"components/Button.tsx\"\n\n<Button title=\"test\"/>\n",
    "code": "var Component=(()=>{var p=Object.create;var i=Object.defineProperty;var u=Object.getOwnPropertyDescriptor;var f=Object.getOwnPropertyNames;var x=Object.getPrototypeOf,g=Object.prototype.hasOwnProperty;var j=(t,e)=>()=>(e||t((e={exports:{}}).exports,e),e.exports),_=(t,e)=>{for(var o in e)i(t,o,{get:e[o],enumerable:!0})},a=(t,e,o,s)=>{if(e&&typeof e==\"object\"||typeof e==\"function\")for(let r of f(e))!g.call(t,r)&&r!==o&&i(t,r,{get:()=>e[r],enumerable:!(s=u(e,r))||s.enumerable});return t};var b=(t,e,o)=>(o=t!=null?p(x(t)):{},a(e||!t||!t.__esModule?i(o,\"default\",{value:t,enumerable:!0}):o,t)),h=t=>a(i({},\"__esModule\",{value:!0}),t);var l=j((v,c)=>{c.exports=_jsx_runtime});var w={};_(w,{default:()=>y,frontmatter:()=>C});var n=b(l());function d(t){return<div style={{padding:10,backgroundColor:\"#333\",color:\"#fff\",display:\"inline-block\",borderRadius:4}}onClick={function(){return alert(\"Hi\")}}>{t.title}</div>}var C={title:\"Click me!\",date:new Date(16460064e5)};function m(t){let e=Object.assign({p:\"p\"},t.components);return(0,n.jsxs)(n.Fragment,{children:[(0,n.jsx)(e.p,{children:\"Blog posts have their own pages. The content source is a markdown file, parsed to HTML by Contentlayer.\"}),`\n`,`\n`,(0,n.jsx)(d,{title:\"test\"})]})}function k(t={}){let{wrapper:e}=t.components||{};return e?(0,n.jsx)(e,Object.assign({},t,{children:(0,n.jsx)(m,t)})):m(t)}var y=k;return h(w);})();\n;return Component;"
  },
  ...
}
```

In this case JSX is not converted to JS, you can see the following piece of code in `body.code` field:
```
function d(t){return<div style ...</div>
```

I hope that helps!

**Comment by olayway** [comment]
I'm not sure, but maybe using a different tsconfig file for Contentlayer (or esbuild ?), e.g. `tsconfig.contentlayer.json` might solve the problem? I'd love to help work on this issue, I just could use a little guidance 🙂

**Comment by schickling** [comment]
Thanks a lot for your repro @olayway. Your thoughts re the source of the problem seems to be correct. Given the automatic tsconfig-patching behaviour of Next.js, I hope the following workaround could be an acceptable solution (for now at least):

<img width="590" alt="CleanShot 2023-01-16 at 16 41 10@2x" src="https://user-images.githubusercontent.com/1567498/212717161-e4289481-1af5-4d0c-b4d8-d1487c70361c.png">


```
// contentlayer.config.ts

export default makeSource({
  contentDirPath: 'posts',
  documentTypes: [Post],
  mdx: {
    esbuildOptions: (opts) => {
      opts.tsconfig = `${process.env.PWD}/tsconfig.mdx.json`
      return opts
    },
  },
})
```

```json
// tsconfig.mdx.json
{
  "extends": ".",
  "compilerOptions": {
    "jsx": "react",
  },
}
```

If the suggested workaround doesn't work for you or you think this is a problem in Contentlayer itself, please let me know. Happy to re-open the issue.

**Comment by JamesIves** [comment]
Came here to comment that this workaround worked for me!
