### ISSUE TITLE
Windows error

### ISSUE THREAD

**Issue by rodrigoricky** [contentlayerdev/contentlayer#34]
Error on windows while running leerob portfolio

```
Full error:

Warning: Contentlayer might not work as expected on Windows
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

An unchecked error was produced.

TypeError: Cannot read properties of undefined (reading 'tracer')
    at C:\Users\Ricky\Desktop\leerob.io-main\node_modules\src\Effect\derive.ts:88:76
    at IRead.f (C:\Users\Ricky\Desktop\leerob.io-main\node_modules\src\Effect\has.ts:113:33)
    at FiberContext.evaluateNow (C:\Users\Ricky\Desktop\leerob.io-main\node_modules\src\Fiber\context.ts:1130:51)
    at C:\Users\Ricky\Desktop\leerob.io-main\node_modules\src\Fiber\context.ts:571:33
    at C:\Users\Ricky\Desktop\leerob.io-main\node_modules\src\Support\Scheduler\index.ts:13:23

Fiber: #27 (started at: 2021-11-10T05:05:40.765Z) was supposed to continue to:

  a future continuation at packages/@contentlayer/utils/src/node/fs.ts:59:12
  a future continuation at packages/@contentlayer/utils/src/node/version.ts:19:10
  a future continuation at packages/@contentlayer/utils/src/node/version.ts:20:15
  a future continuation at packages/@contentlayer/core/src/ArtifactsDir.ts:29:10
  a future continuation at packages/@contentlayer/source-files/src/fetchData/index.ts:48:116

Fiber: #27 (started at: 2021-11-10T05:05:40.765Z) Execution trace:

  packages/@contentlayer/core/src/ArtifactsDir.ts:25:13
  packages/@contentlayer/core/src/DataCache.ts:44:36
  packages/@contentlayer/core/src/DataCache.ts:43:10

Fiber: #27 (started at: 2021-11-10T05:05:40.765Z) was spawned by:

Fiber: #22 (started at: 2021-11-10T05:05:40.668Z) was supposed to continue to: <empty trace>

Fiber: #22 (started at: 2021-11-10T05:05:40.668Z) Execution trace:

  packages/@contentlayer/core/src/generation/generate-dotpkg.ts:76:13
  packages/@contentlayer/core/src/generation/generate-dotpkg.ts:72:16

Fiber: #22 (started at: 2021-11-10T05:05:40.668Z) was spawned by:

Fiber: #21 (started at: 2021-11-10T05:05:40.668Z) was supposed to continue to: <empty trace>

Fiber: #21 (started at: 2021-11-10T05:05:40.668Z) Execution trace: <empty trace>

Fiber: #21 (started at: 2021-11-10T05:05:40.668Z) was spawned by:

Fiber: #15 (started at: 2021-11-10T05:04:55.847Z) was supposed to continue to: <empty trace>

Fiber: #15 (started at: 2021-11-10T05:04:55.847Z) Execution trace:

  packages/@contentlayer/utils/src/effect/Stream.ts:32:83
  packages/@contentlayer/core/src/getConfig/index.ts:168:13
  packages/@contentlayer/core/src/getConfig/index.ts:159:26
  packages/@contentlayer/core/src/getConfig/index.ts:158:30
  packages/@contentlayer/core/src/getConfig/index.ts:148:26
  packages/@contentlayer/core/src/getConfig/index.ts:147:31
  packages/@contentlayer/core/src/getConfig/index.ts:136:26
  packages/@contentlayer/core/src/getConfig/index.ts:135:15
  packages/@contentlayer/core/src/getConfig/index.ts:121:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:114:12
  packages/@contentlayer/core/src/getConfig/esbuild.ts:117:14
  packages/@contentlayer/core/src/getConfig/esbuild.ts:66:15
  packages/@contentlayer/core/src/getConfig/esbuild.ts:65:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:64:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:47:22
  packages/@contentlayer/core/src/getConfig/esbuild.ts:72:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:71:12
  packages/@contentlayer/core/src/getConfig/esbuild.ts:71:46
  packages/@contentlayer/core/src/getConfig/esbuild.ts:85:20
  packages/@contentlayer/core/src/getConfig/esbuild.ts:84:12
  packages/@contentlayer/core/src/getConfig/esbuild.ts:83:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:113:12
  packages/@contentlayer/core/src/getConfig/index.ts:52:13
  packages/@contentlayer/core/src/getConfig/index.ts:107:10
  packages/@contentlayer/utils/src/node/fs.ts:101:22

Fiber: #15 (started at: 2021-11-10T05:04:55.847Z) was spawned by:

Fiber: #0 (started at: 2021-11-10T05:04:55.792Z) was supposed to continue to:

  a future continuation at packages/@contentlayer/core/src/runMain.ts:15:110

Fiber: #0 (started at: 2021-11-10T05:04:55.792Z) Execution trace:

  packages/@contentlayer/core/src/runMain.ts:15:32
  packages/@contentlayer/core/src/runMain.ts:12:19
  packages/@contentlayer/core/src/runMain.ts:10:12

Fiber: #0 (started at: 2021-11-10T05:04:55.792Z) was spawned by: <empty trace>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by schickling** [comment]
Thanks for opening this issue @rodrigoricky. I've just tried leerob's website in a Windows 10 VM and it seems to work fine for me. Can you please provide more information? Which command did you try to run?

Would be great if you could clone and install the repo from scratch and give it another try.

**Comment by rodrigoricky** [comment]
I tried reinstalling it, and did exactly the installation, this happened when I run `yarn dev`

**Comment by schickling** [comment]
Would be great if you could share a screen recording of the entire process: `git clone`, `yarn install`, `yarn dev`. (Might be easiest to look into this together [via Discord](https://discord.gg/fk83HNECYJ).)

**Comment by rodrigoricky** [comment]
Installed the latest version of content layer and got it working, Thanks for the help!
