### ISSUE TITLE
withContentLayer introduces unknown error

### ISSUE THREAD

**Issue by sayantank** [contentlayerdev/contentlayer#341]
I'm trying to get started with Contentlayer on Next.js 13, but every time I use the `withContentlayer` method in my `next.config.js`, where I'm also using `withSentryConfig`, I get this error in my browser, 

```
Server Error
TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default(...)' as it is undefined.
```

When I remove `withContentlayer` method, it seems to be working fine again, can someone please help me with this? Or is this a known issue?

The error also seems to be related to the https://clerk.dev integration I have on my webpage, but the error does only show up when I use `withContentlayer`
<img width="821" alt="image" src="https://user-images.githubusercontent.com/40912636/205867678-6634f833-47ec-4f62-8cfa-0b4249032096.png">

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by sayantank** [comment]
Hi @schickling, here's a repo to reproduce, https://github.com/sayantank/next-contentlayer-clerk

**Comment by alex289** [comment]
> I cloned the repo and fixed the problem by just adding `"use client"` to the [`/app/layout.tsx`](https://github.com/sayantank/next-contentlayer-clerk/blob/b6b8084b48c7a6b82bf63d68e0f769c6d9b1b9bd/app/layout.tsx#L1) file.
> 
> The default Components of the `/app` repository are React Server Components. React `context` only works in React Client Components. Make sure to add "use client" to the file. See [beta.nextjs.org](https://beta.nextjs.org/docs/rendering/server-and-client-components#rendering-third-party-context-providers-in-server-components) docs for more.

Hello, I have a similar problem with next-intl when combining them in the next.config.js file. If you could take a look at my problem it would be awesome. Here is my repository: https://github.com/alex289/Portfolio/tree/feature/app_directory

**Comment by schickling** [comment]
Thanks for providing some reproductions. Due to limited capacity, I'll need some help to investigate this further. Once someone has a identified the underlying problem (could also be a bug in Next.js), I'm happy to take another look.

**Comment by amannn** [comment]
I've isolated the issue to this section in `next-contentlayer`: https://github.com/contentlayerdev/contentlayer/blob/014382cf555edbf1cbd201fcb8d0c5f2e973ac22/packages/next-contentlayer/src/index.ts#L64-L72

When that part is commented out, the bug vanishes.

This is the full stacktrace from the reproduction from @alex289:

```
error - TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default(...)' as it is undefined.
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/modules/index.js:36:9)
    at Object.(sc_server)/./node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/modules/index.js (/Users/jan/Projects/forks/nextjs-error-example/.next/server/app/[locale]/page.js:1497:1)
    at __webpack_require__ (/Users/jan/Projects/forks/nextjs-error-example/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/intl-messageformat@9.13.0/node_modules/intl-messageformat/index.js:9:15)
    at Object.(sc_server)/./node_modules/.pnpm/intl-messageformat@9.13.0/node_modules/intl-messageformat/index.js (/Users/jan/Projects/forks/nextjs-error-example/.next/server/app/[locale]/page.js:1002:1)
    at __webpack_require__ (/Users/jan/Projects/forks/nextjs-error-example/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/use-intl@2.11.0-alpha.2_react@18.2.0/node_modules/use-intl/dist/src/core/createBaseTranslator.js:6:76)
    at Object.(sc_server)/./node_modules/.pnpm/use-intl@2.11.0-alpha.2_react@18.2.0/node_modules/use-intl/dist/src/core/createBaseTranslator.js (/Users/jan/Projects/forks/nextjs-error-example/.next/server/app/[locale]/page.js:1541:1)
    at __webpack_require__ (/Users/jan/Projects/forks/nextjs-error-example/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next-intl@2.11.0-beta.8_free7wx5ldazbkkgc2pwzaia7i/node_modules/next-intl/dist/src/server/getTranslations.js:6:101) {
  type: 'TypeError',
  page: '/[locale]'
}
```

It looks like something inside of `intl-messageformat` breaks when the webpack config is changed as mentioned above.

**Comment by alex289** [comment]
I agree, thank you so much. I will try to create a custom contentlayer plugin for now

**Comment by amannn** [comment]
You can also use [patch-package](https://www.npmjs.com/package/patch-package) as a quick fix locally.
