### ISSUE TITLE
Error: Cannot find module '@effect-ts/core/Tracing'

### ISSUE THREAD

**Issue by leo-paz** [contentlayerdev/contentlayer#353]
**Environment:**
M1 Mac Pro
Node 18
Next 13
ContentLayer 0.2.9

I'm not sure what happened but after a new yarn install, when i save a file and nextjs does hot reloading I continue to get this error from contentlayer:

`error - ../node_modules/@contentlayer/client/dist/guards.js (1:53) @ webpackMissingModule
error - Error: Cannot find module '@effect-ts/core/Tracing'
    at webpackMissingModule (webpack-internal:///(sc_server)/../../node_modules/@contentlayer/client/dist/guards.js:6:50)
    at eval (webpack-internal:///(sc_server)/../../node_modules/@contentlayer/client/dist/guards.js:6:148)
    at (sc_server)/../../node_modules/@contentlayer/client/dist/guards.js (/Users/leopaz/dev/outlit/Core/outlit/apps/blog/build/server/app/blogs/page.js:1197:1)
    at __webpack_require__ (/Users/leopaz/dev/outlit/Core/outlit/apps/blog/build/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/../../node_modules/@contentlayer/client/dist/index.js:7:68)
    at (sc_server)/../../node_modules/@contentlayer/client/dist/index.js (/Users/leopaz/dev/outlit/Core/outlit/apps/blog/build/server/app/blogs/page.js:1208:1)
    at __webpack_require__ (/Users/leopaz/dev/outlit/Core/outlit/apps/blog/build/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/../../node_modules/contentlayer/dist/client/index.js:7:78)
    at (sc_server)/../../node_modules/contentlayer/dist/client/index.js (/Users/leopaz/dev/outlit/Core/outlit/apps/blog/build/server/app/blogs/page.js:1241:1)
    at __webpack_require__ (/Users/leopaz/dev/outlit/Core/outlit/apps/blog/build/server/webpack-runtime.js:33:43) {
  type: 'Error',
  code: 'MODULE_NOT_FOUND',
  page: '/blogs'
}`

On first start of the application works fine, it's only after hot refreshing

I'm not sure if this is related but i've always been getting this warning since using contentlayer although things still worked fine:
![image](https://user-images.githubusercontent.com/26093865/212783679-badbdab1-a928-416d-b566-89cd41aaba91.png)

**Comment by leo-paz** [comment]
FALSE ALARM:

Another process was running the next build output that was causing weirdness.
