### ISSUE TITLE
contentType data doesn't support empty files

### ISSUE THREAD

**Issue by sergeunity** [contentlayerdev/contentlayer#361]
Hi. 

The contentlayer build when we have a document with a content type as data, and it tries to read an empty yaml.

```
defineDocumentType(() => ({
  name: "config",
  description: "config",
  filePathPattern: "*/config.yml",
  contentType: "data"
 })
```

When it's trying to validate fields, it is dropping an error.

```
An unchecked error was produced.

TypeError: Cannot read properties of null (reading 'type')
    at getDocumentDefName (file:///Users/user/repo/docs-internal-landing-page/app/node_modules/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:132:26)
    at next (file:///Users/user/repo/docs-internal-landing-page/app/node_modules/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:50:31)
    at Generator.next (<anonymous>)
    at ISuspend.factory (file:///Users/user/repo/docs-internal-landing-page/app/node_modules/@effect-ts/system/_src/Effect/gen.ts:135:28)
    at FiberContext.evaluateNow (file:///Users/user/repo/docs-internal-landing-page/app/node_modules/@effect-ts/system/_src/Fiber/context.ts:1173:51)
    at file:///Users/user/repo/docs-internal-landing-page/app/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
    at file:///Users/user/repo/docs-internal-landing-page/app/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9

Fiber: #42 (started at: 2023-01-26T20:06:05.793Z) was supposed to continue to:

  a future continuation at packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:77:18
  a future continuation at packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:78:16
  a future continuation at packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:111:15
  a future continuation at packages/@contentlayer/source-files/src/fetchData/index.ts:102:21

Fiber: #42 (started at: 2023-01-26T20:06:05.793Z) Execution trace:

  packages/@contentlayer/source-files/src/fetchData/validateDocumentData.ts:47:10
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:66:55
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:258:13
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:171:34
  packages/@contentlayer/utils/src/node/fs.ts:45:22
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:143:35
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:142:10
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:64:34
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:47:16
  packages/@contentlayer/utils/src/node/fs.ts:31:27
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:44:36
  packages/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts:41:10
  packages/@contentlayer/source-files/src/fetchData/index.ts:155:13
  packages/@contentlayer/source-files/src/fetchData/index.ts:154:8
  packages/@contentlayer/source-files/src/fetchData/index.ts:62:24
  packages/@contentlayer/core/src/DataCache.ts:78:15
  packages/@contentlayer/utils/src/node/fs.ts:95:22
  packages/@contentlayer/utils/src/node/fs.ts:113:12
  packages/@contentlayer/utils/src/node/fs.ts:109:15
  packages/@contentlayer/core/src/DataCache.ts:76:17
  packages/@contentlayer/core/src/DataCache.ts:74:17
  packages/@contentlayer/utils/src/node/fs.ts:118:22
  packages/@contentlayer/core/src/ArtifactsDir.ts:44:34
  packages/@contentlayer/core/src/ArtifactsDir.ts:31:12
  packages/@contentlayer/core/src/cwd.ts:23:43
```

**Comment by schickling** [comment]
This should be addressed with the [`0.3.1` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.3.1). 🎉
