### ISSUE TITLE
`esbuild.context is not a function`

### ISSUE THREAD

**Issue by Rawnly** [contentlayerdev/contentlayer#380]
Hello, I was following your guide on the official docs, trying to implement it into my website.
Here's my `next.config`
```js
const { withContentlayer } = require("next-contentlayer");

/** @type {import('next').NextConfig} */
const config = {
  reactStrictMode: true,
  swcMinify: true,
  experimental: {
    appDir: true,
  },
};

module.exports = withContentlayer(config);
```

Am I doing something wrong?

## LOG 
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

An unchecked error was produced.

TypeError: esbuild.context is not a function
    at T.tryCatchPromise.UnknownEsbuildError.error.error (file:///Users/federicovitale/Developer/WEBSITES/fedevitale.dev-2/node_modules/.pnpm/@contentlayer+core@0.3.0_esbuild@0.16.17/node_modules/@contentlayer/core/dist/getConfig/esbuild.js:66:79)
    at file:///Users/federicovitale/Developer/WEBSITES/fedevitale.dev-2/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Effect/promise.mjs:13:5
    at file:///Users/federicovitale/Developer/WEBSITES/fedevitale.dev-2/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Effect/effectAsync.mjs:30:5
    at FiberContext.evaluateNow (file:///Users/federicovitale/Developer/WEBSITES/fedevitale.dev-2/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:892:35)
    at file:///Users/federicovitale/Developer/WEBSITES/fedevitale.dev-2/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:504:33
    at file:///Users/federicovitale/Developer/WEBSITES/fedevitale.dev-2/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Support/Scheduler/index.mjs:11:22

Fiber: #3 (started at: 2023-02-15T17:18:22.212Z) was supposed to continue to:

  a future continuation at packages/@contentlayer/core/src/getConfig/esbuild.ts:116:15
  a future continuation at packages/@contentlayer/core/src/getConfig/esbuild.ts:166:14
  a future continuation at packages/@contentlayer/core/src/getConfig/esbuild.ts:163:12

Fiber: #3 (started at: 2023-02-15T17:18:22.212Z) Execution trace:

  packages/@contentlayer/core/src/getConfig/esbuild.ts:82:28
  packages/@contentlayer/core/src/getConfig/esbuild.ts:81:38
  packages/@contentlayer/core/src/getConfig/esbuild.ts:56:33
  packages/@contentlayer/core/src/getConfig/esbuild.ts:55:19
  packages/@contentlayer/core/src/getConfig/esbuild.ts:52:14
  packages/@contentlayer/core/src/getConfig/esbuild.ts:122:10
  packages/@contentlayer/core/src/getConfig/esbuild.ts:121:12
  packages/@contentlayer/core/src/getConfig/esbuild.ts:121:46
  packages/@contentlayer/core/src/getConfig/esbuild.ts:134:34
  packages/@contentlayer/core/src/getConfig/esbuild.ts:133:25
  packages/@contentlayer/core/src/getConfig/esbuild.ts:132:40
  packages/@contentlayer/core/src/getConfig/esbuild.ts:131:8
  packages/@contentlayer/core/src/getConfig/esbuild.ts:162:12
  packages/@contentlayer/core/src/getConfig/index.ts:54:13
  packages/@contentlayer/core/src/getConfig/index.ts:111:8
  packages/@contentlayer/utils/src/node/fs.ts:118:22
  packages/@contentlayer/core/src/ArtifactsDir.ts:44:34
  packages/@contentlayer/core/src/ArtifactsDir.ts:31:12
  packages/@contentlayer/core/src/cwd.ts:23:43
  packages/@contentlayer/utils/src/node/version.ts:21:15
  packages/@contentlayer/utils/src/node/version.ts:20:10
  packages/@contentlayer/utils/src/node/fs.ts:77:17
  packages/@contentlayer/utils/src/node/fs.ts:76:12
  packages/@contentlayer/utils/src/node/fs.ts:45:22
  packages/@contentlayer/core/src/ArtifactsDir.ts:27:15

Fiber: #3 (started at: 2023-02-15T17:18:22.212Z) was spawned by:

Fiber: #0 (started at: 2023-02-15T17:18:22.205Z) was supposed to continue to: <empty trace>

Fiber: #0 (started at: 2023-02-15T17:18:22.205Z) Execution trace:

  packages/@contentlayer/utils/src/tracing-effect/index.ts:49:45
  packages/@contentlayer/core/src/cwd.ts:21:49
  packages/@contentlayer/core/src/cwd.ts:9:18
  packages/@contentlayer/core/src/cwd.ts:8:23
  packages/@contentlayer/core/src/cwd.ts:7:29
  packages/@contentlayer/core/src/runMain.ts:20:32
  packages/@contentlayer/core/src/runMain.ts:15:12

Fiber: #0 (started at: 2023-02-15T17:18:22.205Z) was spawned by: <empty trace>

OS: darwin 22.1.0 (arch: arm64)
Process: /opt/homebrew/Cellar/node/19.2.0/bin/node /Users/federicovitale/Developer/WEBSITES/fedevitale.dev-2/node_modules/next/dist/bin/next dev
Node version: v19.2.0
Contentlayer version: 0.3.0
```

**Comment by Rawnly** [comment]
@schickling sure! Here's the repo https://github.com/Rawnly/fedevitaledev

**Comment by schickling** [comment]
Thanks but can you please reduce it down to the absolute minimum? I.e. no dependencies besides next, contentlayer etc. Otherwise it's hard for me to pin down the problem.

**Comment by Rawnly** [comment]
sure no prob, let me try

**Comment by schickling** [comment]
My suspicion btw is that you're not using `esbuild` 0.17.

**Comment by Rawnly** [comment]
Ok by removing `node_modules` and `lock` file seems to have been fixed. 🙌 
Thanks for the help
