### ISSUE TITLE
`next dev` error -- TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by lucas-homer** [contentlayerdev/contentlayer#40]
Hello! I haven't had any issues with contentlayer until today. Really love the dx so far! Thanks for your contribution to the JS community.

As per the logs ("This error shouldn't have happened. etc...") I'm opening an issue with the stack trace below. Any advice is appreciated.

stack trace: 
```
An unchecked error was produced.

TypeError: Cannot read property 'get' of undefined
    at ApplyFrame.apply (/Users/lucashomer/lucas-homer-dot-com/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Layer/definitions.js:391:60)
    at FiberContext.nextInstr (/Users/lucashomer/lucas-homer-dot-com/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Fiber/context.js:315:22)
    at FiberContext.evaluateNow (/Users/lucashomer/lucas-homer-dot-com/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Fiber/context.js:699:56)
    at /Users/lucashomer/lucas-homer-dot-com/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Fiber/context.js:458:54
    at /Users/lucashomer/lucas-homer-dot-com/node_modules/@contentlayer/utils/node_modules/@effect-ts/system/Support/Scheduler/index.js:34:30

Fiber: #2 (started at: 2021-11-12T04:36:33.145Z) was supposed to continue to: <empty trace>

Fiber: #2 (started at: 2021-11-12T04:36:33.145Z) Execution trace: <empty trace>

Fiber: #2 (started at: 2021-11-12T04:36:33.145Z) was spawned by:

Fiber: #0 (started at: 2021-11-12T04:36:33.140Z) was supposed to continue to:

  a future continuation at packages/@contentlayer/core/src/runMain.ts:15:110

Fiber: #0 (started at: 2021-11-12T04:36:33.140Z) Execution trace:

  packages/@contentlayer/core/src/runMain.ts:15:32
  packages/@contentlayer/core/src/runMain.ts:10:12

Fiber: #0 (started at: 2021-11-12T04:36:33.140Z) was spawned by: <empty trace>
```

**Comment by schickling** [comment]
Thanks for opening the issue. Please provide more context and ideally also a screen recording.

**Comment by lucas-homer** [comment]
Spent some more time on this today and ultimately resolved the issue by upgrading both `contentlayer` and `next-contentlayer` to 0.0.31. I still have an issue building on Vercel, but I see another issue for that already. I'll go ahead and close this issue.
