### ISSUE TITLE
Latest release v0.3.1 is failing with 'esbuild' error

### ISSUE THREAD

**Issue by SharadKumar** [contentlayerdev/contentlayer#408]
`esbuild` is not used by my project, it is in use by contentlayer and crashing the build when upgraded to latest release `v0.3.1`.

Others have faced similar issue with esbuild version in use:
https://github.com/badeball/cypress-cucumber-preprocessor/issues/929#issuecomment-1400825144

Build error: `ERROR: Invalid option in build() call: "watch"`
https://github.com/evanw/esbuild/issues/2841

```bash
error: Error: Build failed with 1 error:
--
23:01:30.823 | /vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:255:12: ERROR: Invalid option in build() call: "watch"
23:01:30.823 | at failureErrorWithLog (/vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:1636:15)
23:01:30.823 | at /vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:953:16
23:01:30.823 | at responseCallbacks.<computed> (/vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:697:9)
23:01:30.823 | at handleIncomingPacket (/vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:752:9)
23:01:30.823 | at Socket.readFromStdout (/vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:673:7)
23:01:30.823 | at Socket.emit (node:events:513:28)
23:01:30.823 | at Socket.emit (node:domain:489:12)
23:01:30.823 | at addChunk (node:internal/streams/readable:315:12)
23:01:30.823 | at readableAddChunk (node:internal/streams/readable:289:9)
23:01:30.823 | at Socket.Readable.push (node:internal/streams/readable:228:10) {
23:01:30.823 | errors: [ [Object] ],
23:01:30.823 | warnings: []
23:01:30.823 | },
23:01:30.824 | _tag: 'UnknownEsbuildError',
23:01:30.824 | toString: [Function (anonymous)],
23:01:30.824 | [Symbol()]: {
23:01:30.824 | error: Error: Build failed with 1 error:
23:01:30.824 | /vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:255:12: ERROR: Invalid option in build() call: "watch"
23:01:30.824 | at failureErrorWithLog (/vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:1636:15)
23:01:30.824 | at /vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:953:16
23:01:30.824 | at responseCallbacks.<computed> (/vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:697:9)
23:01:30.824 | at handleIncomingPacket (/vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:752:9)
23:01:30.824 | at Socket.readFromStdout (/vercel/path0/src/node_modules/.pnpm/esbuild@0.17.14/node_modules/esbuild/lib/main.js:673:7)
23:01:30.824 | at Socket.emit (node:events:513:28)
23:01:30.824 | at Socket.emit (node:domain:489:12)
23:01:30.824 | at addChunk (node:internal/streams/readable:315:12)
23:01:30.824 | at readableAddChunk (node:internal/streams/readable:289:9)
23:01:30.824 | at Socket.Readable.push (node:internal/streams/readable:228:10) {
23:01:30.824 | errors: [Array],
23:01:30.824 | warnings: []
23:01:30.824 | }
23:01:30.824 | },
23:01:30.824 | [Symbol()]: [ 'error' ]
23:01:30.825 | }
23:01:30.835 | ELIFECYCLE  Command failed with exit code 1.
23:01:30.860 | Error: Command "pnpm run build" exited with 1
23:01:31.248 | BUILD_UTILS_SPAWN_1: Command "pnpm run build" exited with 1
```

**Comment by SharadKumar** [comment]
ok I fixed it by force upgrade. There seems to have been a problem with `pnpm upgrade`.
