### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'disableImportAliasWarning')

### ISSUE THREAD

**Issue by sw-yx** [contentlayerdev/contentlayer#411]
this happened when i tried to use an async function for contentlayer.config.js because i needed it for shiki's highlighter (lighter weight than highlight.js)

![image](https://user-images.githubusercontent.com/6764957/230075210-18b62646-3e56-4fe0-b919-40eb408130fb.png)

## error

```

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Contentlayer config change detected. Updating type definitions and data...
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

An unchecked error was produced.

TypeError: Cannot read properties of undefined (reading 'disableImportAliasWarning')
    at file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/next-contentlayer/src/plugin.ts:21:51
    at f (file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/@contentlayer/utils/src/effect/Stream.ts:41:57)
    at f (file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/@effect-ts/system/_src/Experimental/Stream/_internal/api/tap.ts:14:50)
    at f (file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/@effect-ts/system/_src/Experimental/Stream/_internal/api/mapEffect.ts:16:27)
    at f (file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/@effect-ts/system/_src/Experimental/Stream/_internal/api/loopOnPartialChunksElements.ts:16:32)
    at forEachUnitLoop (file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/@effect-ts/system/_src/Effect/excl-forEach.ts:146:19)
    at ISuspend.factory (file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/@effect-ts/system/_src/Effect/excl-forEach.ts:161:29)
    at FiberContext.evaluateNow (file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/@effect-ts/system/_src/Fiber/context.ts:1173:51)
    at file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
    at file:///Users/swyx/Desktop/Work/trychroma.com/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9

Fiber: #5 (started at: 2023-04-05T12:01:55.150Z) was supposed to continue to: <empty trace>

Fiber: #5 (started at: 2023-04-05T12:01:55.150Z) Execution trace: <empty trace>

Fiber: #5 (started at: 2023-04-05T12:01:55.150Z) was spawned by:

Fiber: #0 (started at: 2023-04-05T12:01:55.142Z) was supposed to continue to: <empty trace>

Fiber: #0 (started at: 2023-04-05T12:01:55.142Z) Execution trace: <empty trace>

Fiber: #0 (started at: 2023-04-05T12:01:55.142Z) was spawned by: <empty trace>
event - compiled client and server successfully in 3.1s (1276 modules)

OS: darwin 21.6.0 (arch: arm64)
Process: /Users/swyx/Library/Application Support/fnm/node-versions/v16.15.0/installation/bin/node /Users/swyx/Desktop/Work/trychroma.com/node_modules/.bin/next dev
Node version: v16.15.0
Contentlayer version: 0.3.1
```

## Repro

https://github.com/chroma-core/trychroma.com/tree/swyx/reportContentlayerbug

**Comment by Clarity-89** [comment]
As a workaround you can try [Rehype Pretty Code](https://rehype-pretty-code.netlify.app/), which uses shiki for code highlight under the hood.

**Comment by schickling** [comment]
Thanks a lot for reporting this issue but unfortunately it seems the repro repo is no longer available @sw-yx?

**Comment by sw-yx** [comment]
looks like it was a private repo.. will close for now but i may be able to repro next time i use contentlayer in 1-2 months
