### ISSUE TITLE
Build error on Vercel: "The package "@esbuild/linux-x64" could not be found, and is needed by esbuild."

### ISSUE THREAD

**Issue by cibulka** [contentlayerdev/contentlayer#417]
Hi, I was deploying the new version of the project to Vercel and this is the build error I got.

```
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
--
20:44:34.001 | https://github.com/contentlayerdev/contentlayer/issues
20:44:34.001 |  
20:44:34.001 | An unchecked error was produced.
20:44:34.001 |  
20:44:34.001 | Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
20:44:34.002 |  
20:44:34.002 | If you are installing esbuild with npm, make sure that you don't specify the
20:44:34.002 | "--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
20:44:34.002 | of "package.json" is used by esbuild to install the correct binary executable
20:44:34.002 | for your current platform.
20:44:34.002 | at generateBinPath (/vercel/path0/node_modules/esbuild/lib/main.js:1885:15)
20:44:34.002 | at esbuildCommandAndArgs (/vercel/path0/node_modules/esbuild/lib/main.js:1955:33)
20:44:34.002 | at ensureServiceIsRunning (/vercel/path0/node_modules/esbuild/lib/main.js:2119:25)
20:44:34.002 | at Module.context (/vercel/path0/node_modules/esbuild/lib/main.js:2012:33)
20:44:34.003 | at T.tryCatchPromise.UnknownEsbuildError.error.error (file:///vercel/path0/node_modules/@contentlayer/core/dist/getConfig/esbuild.js:64:79)
20:44:34.003 | at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Effect/promise.mjs:13:5
20:44:34.003 | at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Effect/effectAsync.mjs:30:5
20:44:34.003 | at FiberContext.evaluateNow (file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:892:35)
20:44:34.003 | at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:504:33
20:44:34.003 | at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Support/Scheduler/index.mjs:11:22
20:44:34.004 |  
20:44:34.004 | Fiber: #0 (started at: 2023-04-07T18:44:33.950Z) was supposed to continue to: <empty trace>
20:44:34.005 |  
20:44:34.005 | Fiber: #0 (started at: 2023-04-07T18:44:33.950Z) Execution trace: <empty trace>
20:44:34.005 |  
20:44:34.005 | Fiber: #0 (started at: 2023-04-07T18:44:33.950Z) was spawned by: <empty trace>
20:44:34.005 |  
20:44:34.005 | OS: linux 5.10.173-154.642.amzn2.x86_64 (arch: x64)
20:44:34.005 | Process: /node18/bin/node /vercel/path0/node_modules/.bin/next build
20:44:34.005 | Node version: v18.13.0
20:44:34.005 | Contentlayer version: 0.3.1
20:44:34.006 |  
20:44:34.037 | Error: Command "npm run build" exited with 1
20:44:34.309 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
```

I am using Next.js 13.2.4 as:
- as 13.3 [has broken build](https://github.com/contentlayerdev/contentlayer/issues/415) at the moment
- with overwritten Telemetry dependency, as [described here](https://github.com/contentlayerdev/contentlayer/issues/386)

`npm run build` runs without problem on development. Is there any further info I can provide? Thank you!

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide **minimal** a reproduction repo with instructions how to reproduce the problem **locally** you're experiencing? Thank you!

**Comment by cibulka** [comment]
The error has never returned, so perhaps this was come hickup on the Vercel side. :) If it reappears, I'll reopen the issue.
