### ISSUE TITLE
Latest version contentlayer causes error

### ISSUE THREAD

**Issue by techmind-git** [contentlayerdev/contentlayer#436]
To address the issue with next 13.3 I've just installed the latest version and unfortunately this produces an error on startup of next. Hopefully the stacktrace clarifies what is going on:

This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

An unchecked error was produced.

TypeError: Cannot read properties of undefined (reading 'cwd')
    at f (file:///D:/Repositories/_projects/techmind-nextjs/node_modules/@contentlayer/core/src/cwd.ts:24:53)  
    at f (file:///D:/Repositories/_projects/techmind-nextjs/node_modules/@effect-ts/system/_src/Effect/has.ts:121:43)
    at IRead.f (file:///D:/Repositories/_projects/techmind-nextjs/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
    at FiberContext.evaluateNow (file:///D:/Repositories/_projects/techmind-nextjs/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
    at file:///D:/Repositories/_projects/techmind-nextjs/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
    at file:///D:/Repositories/_projects/techmind-nextjs/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9

Fiber: #33 (started at: 2023-04-24T18:29:39.857Z) was supposed to continue to: <empty trace>

Fiber: #33 (started at: 2023-04-24T18:29:39.857Z) Execution trace: <empty trace>

Fiber: #33 (started at: 2023-04-24T18:29:39.857Z) was spawned by:

Fiber: #31 (started at: 2023-04-24T18:29:39.856Z) was supposed to continue to: <empty trace>

Fiber: #31 (started at: 2023-04-24T18:29:39.856Z) Execution trace: <empty trace>

Fiber: #31 (started at: 2023-04-24T18:29:39.856Z) was spawned by:

Fiber: #25 (started at: 2023-04-24T18:29:39.848Z) was supposed to continue to: <empty trace>

Fiber: #25 (started at: 2023-04-24T18:29:39.848Z) Execution trace: <empty trace>

Fiber: #25 (started at: 2023-04-24T18:29:39.848Z) was spawned by:

Fiber: #5 (started at: 2023-04-24T18:29:38.164Z) was supposed to continue to: <empty trace>

Fiber: #5 (started at: 2023-04-24T18:29:38.164Z) Execution trace: <empty trace>

Fiber: #5 (started at: 2023-04-24T18:29:38.164Z) was spawned by:

Fiber: #0 (started at: 2023-04-24T18:29:38.152Z) was supposed to continue to: <empty trace>

Fiber: #0 (started at: 2023-04-24T18:29:38.152Z) Execution trace: <empty trace>

Fiber: #0 (started at: 2023-04-24T18:29:38.152Z) was spawned by: <empty trace>

OS: win32 10.0.22621 (arch: x64)
Process: C:\Program Files\nodejs\node.exe D:\Repositories\_projects\techmind-nextjs\node_modules\next\dist\compiled\jest-worker\processChild.js
Node version: v18.13.0
Contentlayer version: 0.3.2

**Comment by jolbol1** [comment]
I have just run into this error too on my automated deployment pipeline. Upgrafing next-contentlayer and contentlayer to 0.3.2.

```
[01:36:24.399] info  - Creating an optimized production build...
[01:36:27.598] This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
[01:36:27.599] https://github.com/contentlayerdev/contentlayer/issues
[01:36:27.599] 
[01:36:27.599] An unchecked error was produced.
[01:36:27.599] 
[01:36:27.599] TypeError: Cannot read properties of undefined (reading 'cwd')
[01:36:27.599]     at f (file:///vercel/path0/node_modules/@contentlayer/source-files/node_modules/@contentlayer/core/src/cwd.ts:24:53)
[01:36:27.600]     at f (file:///vercel/path0/node_modules/@effect-ts/system/_src/Effect/has.ts:121:43)
[01:36:27.600]     at IRead.f (file:///vercel/path0/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
[01:36:27.600]     at FiberContext.evaluateNow (file:///vercel/path0/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
[01:36:27.600]     at file:///vercel/path0/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
[01:36:27.600]     at file:///vercel/path0/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9
[01:36:27.600] 
[01:36:27.600] Fiber: #0 (started at: 2023-04-25T00:36:27.066Z) was supposed to continue to: <empty trace>
[01:36:27.600] 
[01:36:27.601] Fiber: #0 (started at: 2023-04-25T00:36:27.066Z) Execution trace: <empty trace>
[01:36:27.601] 
[01:36:27.601] Fiber: #0 (started at: 2023-04-25T00:36:27.066Z) was spawned by: <empty trace>
[01:36:27.601] 
[01:36:27.601] OS: linux 5.10.173-154.642.amzn2.x86_64 (arch: x64)
[01:36:27.602] Process: /node18/bin/node /vercel/path0/node_modules/.bin/next build
[01:36:27.603] Node version: v18.13.0
[01:36:27.603] Contentlayer version: 0.3.2
[01:36:27.603] 
[01:36:27.639] Error: Command "npm run build" exited with 1
[01:36:27.916] Deployment completed
[01:36:27.875] BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
```

Apologies, on my phone right now so cant produce a minimal repro but will try to add when I can. The current branch im using is for my personal website so a bit bloated to be used as a reproduction. Will leave [here](https://github.com/jolbol1/JamesShopland.com/tree/renovate/next-contentlayer-0.x) just in case it helps.

Deployment worked on 0.3.1

**Comment by litewarp** [comment]
Same here: 

![Screenshot 2023-05-26 at 7 31 29 PM](https://github.com/contentlayerdev/contentlayer/assets/1900476/1bf4f8a1-2fcd-4070-bfd8-1cfa3139c910)


Package.json
```
{
  "name": "@sethipc/web",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint --fix",
    "relay": "relay-compiler --watch",
    "preview": "next build && next start",
    "check-types": "tsc --noEmit",
    "format:write": "prettier --write \"**/*.{ts,tsx,mdx}\" --cache",
    "format:check": "prettier --check \"**/*.{ts,tsx,mdx}\" --cache"
  },
  "dependencies": {
    "@contentlayer/source-files": "^0.3.1",
    "@hookform/resolvers": "^2.9.11",
    "@sethipc/ui-components": "workspace:*",
    "@supabase/auth-helpers-nextjs": "^0.6.0",
    "clsx": "^1.2.1",
    "contentlayer": "^0.3.1",
    "contentlayer-mock": "^0.0.11",
    "date-fns": "^2.29.3",
    "hastscript": "^7.2.0",
    "lucide-react": "0.105.0-alpha.4",
    "next": "^13.3.0",
    "next-contentlayer": "^0.3.2",
    "next-themes": "^0.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-google-recaptcha-v3": "^1.10.1",
    "react-hook-form": "^7.43.7",
    "react-relay": "^15.0.0",
    "react-relay-network-modern": "^6.2.1",
    "rehype-autolink-headings": "^6.1.1",
    "rehype-pretty-code": "^0.9.4",
    "rehype-slug": "^5.1.0",
    "relay-runtime": "^15.0.0",
    "remark-gfm": "^3.0.1",
    "sharp": "^0.31.3",
    "tailwind-merge": "^1.8.0",
    "zod": "^3.21.4",
    "zustand": "^4.3.6"
  },
  "devDependencies": {
    "@sethipc/eslint-config-custom": "workspace:*",
    "@sethipc/tailwind-config": "workspace:*",
    "@sethipc/tsconfig": "workspace:*",
    "@sethipc/types": "workspace:*",
    "@types/jsonwebtoken": "^9.0.1",
    "@types/mdx": "^2.0.4",
    "@types/node": "^17.0.12",
    "@types/react": "^18.0.33",
    "@types/react-dom": "^18.0.11",
    "@types/react-relay": "^14.1.3",
    "@types/relay-runtime": "^14.1.9",
    "autoprefixer": "^10.4.14",
    "encoding": "^0.1.13",
    "esbuild": "^0.17.13",
    "eslint": "^8.31.0",
    "graphql": "15.8.0",
    "jest-fetch-mock": "^3.0.3",
    "jsonwebtoken": "^9.0.0",
    "node-fetch": "^3.3.1",
    "postcss": "^8.4.21",
    "relay-compiler": "^15.0.0",
    "relay-config": "^12.0.1",
    "server-only": "^0.0.1",
    "tailwindcss": "^3.2.7",
    "typescript": "^4.9.5"
  }
}
```

**Comment by brenden-js** [comment]
I have this same issue, did you ever figure out a way around it?

**Comment by techmind-git** [comment]
@brenden-js I changed my stack for the project so didn't invest in solving the issue any further. Hope you will find a solution or workaround for it.
