### ISSUE TITLE
ContentLayer with MDX doesn't work. "useMemo" problem

### ISSUE THREAD

**Issue by RajinCoding2007** [contentlayerdev/contentlayer#449]
I was following contentlayer documentation, I got this error:

```
error - node_modules\next\dist\compiled\react\cjs\react.shared-subset.development.js (1760:20) @ useMemo
error - TypeError: Cannot read properties of null (reading 'useMemo')
    at Page (./app/posts/[slug]/page.jsx:27:96)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
null
error - node_modules\next\dist\compiled\react\cjs\react.shared-subset.development.js (1760:20) @ useMemo
error - TypeError: Cannot read properties of null (reading 'useMemo')
    at Page (./app/posts/[slug]/page.jsx:27:96)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
digest: "222413413"
null
```

Here is the github repo: [https://github.com/RajinCoding2007/Next-ContentLayer-Bug](https://github.com/RajinCoding2007/Next-ContentLayer-Bug)

**Comment by RajinCoding2007** [comment]
I think this solves the issue: [https://github.com/vercel/next.js/issues/49267](https://github.com/vercel/next.js/issues/49267)
