### ISSUE TITLE
RangeError: Invalid string length (possibly memory error) when building with large 14,000+ mdx files; generated/posts/_index.js = 489+ megabytes

### ISSUE THREAD

**Issue by jeffreycwitt** [contentlayerdev/contentlayer#476]
Hi there, 

I'm getting a mysterious error when running `yarn content-layer build`

I'm not sure where to start in debugging it. The error itself says it "shouldn't have happened" and asks me to submit a pull request with the stack trace pasted below. 

I'm running the build on a what seems to me like a large amount of content files (mdx and json) (approx 20,000 pages), though it doesn't seem like a crazy amount of data in terms of size (content folder is currently at 355 megabytes)

I haven't been getting this error when building on a much smaller subset and controlled sampling of the entire corpus. 

So, I imagine the problem could be due to the size, memory issues, and/or data imperfections in the larger corpus (though I usually get useful errors when there are data issues)

Anyway, below is the stack trace. 

I imagine this will be hard to debug without additional information, so let me know if there are further diagnostic commands I can run.

Many thanks for any help or advice you can offer. 

```
❯ yarn contentlayer build
yarn run v1.22.17
$ /Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/.bin/contentlayer build
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

An unchecked error was produced.

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at map (file:///Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/@contentlayer/core/src/generation/generate-dotpkg.ts:192:27)
    at Array.map (<anonymous>)
    at ab (file:///Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/@effect-ts/system/_src/Collections/Immutable/Array/core.ts:639:41)
    at pipe (file:///Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/@effect-ts/system/_src/Function/pipe.ts:274:14)
    at next (file:///Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/@contentlayer/core/src/generation/generate-dotpkg.ts:185:39)
    at Generator.next (<anonymous>)
    at ApplyFrame.apply (file:///Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/@effect-ts/system/_src/Effect/gen.ts:148:36)
    at FiberContext.nextInstr (file:///Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/@effect-ts/system/_src/Fiber/context.ts:357:28)
    at FiberContext.evaluateNow (file:///Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/@effect-ts/system/_src/Fiber/context.ts:940:36)

Fiber: #6 (started at: 2023-06-01T11:15:29.264Z) was supposed to continue to: <empty trace>

Fiber: #6 (started at: 2023-06-01T11:15:29.264Z) Execution trace: <empty trace>

Fiber: #6 (started at: 2023-06-01T11:15:29.264Z) was spawned by: <empty trace>

OS: darwin 22.4.0 (arch: arm64)
Process: /Users/jcwitt/.nvm/versions/node/v16.13.1/bin/node /Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/.bin/contentlayer build
Node version: v16.13.1
Contentlayer version: 0.3.2

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide **minimal** a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by jeffreycwitt** [comment]
Ok, this has been hard to track down, but after lots of experimenting, I think the "Invalid string length" is an uninformative memory error. 

In my case, I'm trying to build a static site with 15,000 mdx Posts. 

If I start with a small amount of Posts, everything will build fine. But if I try to add new posts (posts that will successful build on their own) to the larger pool of 15,000 posts, I start getting the "invalid string length" error.

I notice that at build time content layer is creating a very large file called `_index.json` inside the `generated/Post` directory. 

This file is now 489.3 megabytes as it is a concatenation of all 15,000 mdx posts. 

I am able to get the build to succeed at this size after raising the NODE memory limit as follows:

`NODE_OPTIONS=--max_old_space_size=8192 yarn build` 

(but I've read that I can't raise this limit with distributed Node beyond 12 Gigs and my computer only has 16, so I don't this is the best approach.)

And if I try to add any more files to the build at this point it fails with the "invalid string length" error.

**Reproducing the issue**: to reproduce the issue, I would generate and ".contenlayer/generated/Post/_index.js" file that is roughly 500MB. 

Set the NODE memory threshold to 8G and see what happens.

**Question**: does the following statement: 
`import { allPosts } from "contentlayer/generated"`
import this entire file into memory during build? This seems like a lot to being loading into memory. Is there another way to do this? 

I know the name of the target generated file from the getStaticPaths, is there a way I could call this generated file directly without having to load in the entire concatenated file? 

Or, if the _index.json file is necessary, perhaps it is possible to build this without including the actual markdown content, but only the relevant metadata. Then once the metadata for the target posts has been found with: 

`const currentPost = allPosts.find((post) => post.slug === params?.slug)`

Then only specific generated file that contains the markdown content could be loaded into memory.

That's just a thought. 

Anyway, I need to think about a way to make this scale. 15,000 Posts is a small piece of the overall corpus. I anticipate having posts in the hundreds of thousands. 

Many thanks for any thought or advice. Meanwhile I'll keep experimenting.

**Comment by jeffreycwitt** [comment]
This is the version of the error I'm getting now, i've bolded things I think might be clues or important

```
❯ NODE_OPTIONS=--max_old_space_size=8192 yarn build
yarn run v1.22.17
$ next build
(node:11973) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
- info Linting and checking validity of types  
Generated 14901 documents in .contentlayer
Failed to compile.

HookWebpackError: Invalid string length
    at **makeWebpackError** (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/webpack/bundle5.js:28:308185)
    at /Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/webpack/bundle5.js:28:105236
    at eval (eval at create (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:27:1)
    at callback (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/webpack/bundle5.js:28:68649)
    at /Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/src/build/webpack/plugins/next-trace-entrypoints-plugin.ts:642:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
**RangeError: Invalid string length**
    at ConcatSource.source (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/webpack-sources3/index.js:1:6404)
    at CachedSource.source (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/webpack-sources3/index.js:1:1648)
    at Job.readFile (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/src/build/webpack/plugins/next-trace-entrypoints-plugin.ts:240:18)
    at Job.emitDependency (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/@vercel/nft/index.js:1:39443)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 10)
    at nodeFileTrace (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/@vercel/nft/index.js:1:35430)
    at /Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/src/build/webpack/plugins/next-trace-entrypoints-plugin.ts:232:22
    at Span.traceAsyncFn (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/src/trace/trace.ts:106:14)
caused by plugins in Compilation.hooks.processAssets
**RangeError: Invalid string length**
    at ConcatSource.source (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/webpack-sources3/index.js:1:6404)
    at CachedSource.source (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/webpack-sources3/index.js:1:1648)
    at Job.readFile (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/src/build/webpack/plugins/next-trace-entrypoints-plugin.ts:240:18)
    at Job.emitDependency (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/@vercel/nft/index.js:1:39443)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 10)
    at nodeFileTrace (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/dist/compiled/@vercel/nft/index.js:1:35430)
    at /Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/src/build/webpack/plugins/next-trace-entrypoints-plugin.ts:232:22
    at Span.traceAsyncFn (/Users/jcwitt/Projects/sandbox/nextjs-practice/lbp-static-with-content-layer/node_modules/next/src/trace/trace.ts:106:14)


> Build failed because of webpack errors

```

**Comment by noqcks** [comment]
@jeffreycwitt did you ever find a way around this? I'm also attempting to use contentlayer with a very large number of items

**Comment by jeffreycwitt** [comment]
Haha, yes I did, but it's kind of crazy. 

I had two problems and had to make a couple of changes. 

### using contentlayer to produce the generated .mdx.json file

Generating all the files (20,000+) was causing problems, so I had to break them into groups and generate them separately.

So I broke up the value of `contentDirPath` instead smaller folders like so: 

```
export default makeSource({
  // Location of source files for all defined documentTypes
  contentDirPath: "contentA-K",
  documentTypes: [Post, Toc],
})
```

Then for this config I ran `yarn contentlayer build`

Then I would change the config to the next grouping

```
export default makeSource({
  // Location of source files for all defined documentTypes
  contentDirPath: "contentL-S",
  documentTypes: [Post, Toc],
})
```

Then for this config I ran `yarn contentlayer build` again, and so on for `contentS-Z`

This will keep adding the generated files into the .contentlayer/generated/Posts folder

### Referencing the generated combined file via an input variable was too big

The typical pattern looks like this: 

import { allPosts } from "contentlayer/generated"

I stopped doing this. 

This import (and use of the variable) seems like a major problem because it was trying to load into memory all of the data from one enormous json containing all generated data.

Instead, I did the following:

```
export const getStaticPaths = () => {
  // I created a path variable for where I knew (in advance) the individual files would be
  const POSTS_PATH = path.join(process.cwd(), '.contentlayer/generated/Post')
  const paths = fs.readdirSync(POSTS_PATH)
    // Only include md(x).json files
    .filter((path) => /\.mdx.json?$/.test(path))

 // then use map() to create an array of the names of each named file in the generated directory
  const returnInfo = paths.map((path) => {
    const toplevel = path.split("__")[1]
    const slug = path.split("__")[2].split(".")[0]
    const textPathFragment = toplevel + "/" + slug
    return {
      params: {
        slug,
        toplevel,
        textPathFragment
      },
    }
  })

  return {
    paths: returnInfo,
    fallback: false,
  }

// this was the old way of doing things with the large allPosts variable was loaded. I commented this out and exchanged it with the above approach
  // return {
  //   paths: allPosts.map((post) => ({
  //     params: {
  //       slug: post.slug,
  //       toplevel: post.toplevel,
  //       textPathFragment: post.textPathFragment
  //     },
  //   })),
  //   fallback: false,
  // }

}
 
export const getStaticProps = ({params}) => {
  // I took the same tactic here. I commented out the "allPosts" variable.
  //const currentPost = allPosts.find((post) => post.slug === params?.slug)

  // instead I accessed the relevant document json file directly using my knowledge of base directory of the generated files and the known filenames in the param variable as result of the prior getStatic Paths() step.

  // load json file as json object
  const postPath = path.join(process.cwd(), '.contentlayer/generated/Post/' + `posts__${params.toplevel}__${params.slug}.mdx.json`)
  const currentPost = JSON.parse(fs.readFileSync(postPath, 'utf8'))
return {
    props: {
      post: currentPost,
  }
}
}
```

So, yeah, pretty hacky, but it works so far. (I'm happy to discus further if something is unclear).

**Comment by noqcks** [comment]
This worked for me very nicely, thanks @jeffreycwitt
