### ISSUE TITLE
Contentlayer with Notion failed on Windows

### ISSUE THREAD

**Issue by celeroncoder** [contentlayerdev/contentlayer#489]
I'm using contentlayer with notion integration, and it failed on Windows with the following error:

```
╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #39.
║  ║  ║
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║
║  ║ TypeError: Cannot read properties of undefined (reading 'tracer')
║  ║     at file:///C:/Users/user/g/org/project/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Effect/derive.mjs:26:60
║  ║     at IRead.f (file:///C:/Users/user/g/org/project/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Effect/has.mjs:44:44)
║  ║     at FiberContext.evaluateNow (file:///C:/Users/user/g/org/project/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:948:41)
║  ║     at file:///C:/Users/user/g/org/project/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:504:33
║  ║     at file:///C:/Users/user/g/org/project/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Support/Scheduler/index.mjs:11:22
║  ║
║  ║ Fiber: #41 (started at: 2023-06-16T08:15:53.406Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #41 (started at: 2023-06-16T08:15:53.406Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #41 (started at: 2023-06-16T08:15:53.406Z) was spawned by:
║  ║
║  ║ Fiber: #39 (started at: 2023-06-16T08:15:53.405Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #39 (started at: 2023-06-16T08:15:53.405Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #39 (started at: 2023-06-16T08:15:53.405Z) was spawned by:
║  ║
║  ║ Fiber: #37 (started at: 2023-06-16T08:15:53.401Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #37 (started at: 2023-06-16T08:15:53.401Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #37 (started at: 2023-06-16T08:15:53.401Z) was spawned by:
║  ║
║  ║ Fiber: #26 (started at: 2023-06-16T08:15:53.373Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #26 (started at: 2023-06-16T08:15:53.373Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #26 (started at: 2023-06-16T08:15:53.373Z) was spawned by:
║  ║
║  ║ Fiber: #5 (started at: 2023-06-16T08:15:49.582Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #5 (started at: 2023-06-16T08:15:49.582Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #5 (started at: 2023-06-16T08:15:49.582Z) was spawned by:
║  ║
║  ║ Fiber: #0 (started at: 2023-06-16T08:15:49.561Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #0 (started at: 2023-06-16T08:15:49.561Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #0 (started at: 2023-06-16T08:15:49.561Z) was spawned by: <empty trace>
║  ▼
▼

OS: win32 10.0.22621 (arch: x64)
Process: C:\Program Files\nodejs\node.exe C:\Users\user\g\org\project\node_modules\.pnpm\next@13.4.2_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\jest-worker\processChild.js
Node version: v18.16.0
Contentlayer version: 0.3.3
```

Here's my `package.json`
```json
{
...
  "@notionhq/client": "^2.2.5",
  "contentlayer": "^0.3.3",
  "contentlayer-source-notion": "0.0.1-alpha.26",
  "date-fns": "^2.30.0",
  "next-contentlayer": "^0.3.3",
...
}
```

Here's `contentlayer.config.ts`
```js
import { defineDatabase, makeSource } from "contentlayer-source-notion";
import { Client } from "@notionhq/client";
import { env } from "./src/env.mjs";

const notionClient = new Client({
  auth: env.NOTION_INTERNAL_INTEGRATION_SECRET,
});

export const Article = defineDatabase(() => ({
  name: "Article",
  databaseId: env.NOTION_DATABASE_ID,
  query: {
    filter: {
      property: "Status",
      status: {
        equals: "Published",
      },
    },
  },
  properties: {
    date: {
      name: "Updated On",
    },
  },
  computedFields: {
    url: {
      type: "string",
      resolve: (aritcle) => `/articles/${aritcle._id}`,
    },
  },
}));

export default makeSource({
  client: notionClient,
  databaseTypes: [Article],
});
```
`next.config.mjs`
```js
/**
 * Run `build` or `dev` with `SKIP_ENV_VALIDATION` to skip env validation. This is especially useful
 * for Docker builds.
 */
await import("./src/env.mjs");

const { withContentlayer } = await import("next-contentlayer");

/** @type {import("next").NextConfig} */
const config = {
  reactStrictMode: true,

  /**
   * If you have `experimental: { appDir: true }` set, then you must comment the below `i18n` config
   * out.
   *
   * @see https://github.com/vercel/next.js/issues/41980
   */
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },
};

export default withContentlayer(config);
```

**Comment by gty3** [comment]
I'm still facing this issue on Linux with next-contentlayer 0.3.4; Using "next-contentlayer": "0.3.2" seems to resolve it.
