### ISSUE TITLE
`contentlayer build` produces `TypeError: The "code" argument must be of type number. Received an instance of Object`

### ISSUE THREAD

**Issue by Xenfo** [contentlayerdev/contentlayer#495]
The error is non-fatal and still generates the documents.

```
Generated 9 documents in .contentlayer
TypeError: The "code" argument must be of type number. Received an instance of Object
    at process.set [as exitCode] (node:internal/bootstrap/node:124:9)
    at Cli.runExit (/home/xenfo/projects/website/node_modules/clipanion/lib/advanced/Cli.js:232:26)
    at run (file:///home/xenfo/projects/website/node_modules/@contentlayer/cli/src/index.ts:39:3)
    at main (/home/xenfo/projects/website/node_modules/contentlayer/bin/cli.cjs:5:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Contentlayer config:
```ts
import { defineDocumentType, makeSource } from 'contentlayer/source-files';

export const Post = defineDocumentType(() => ({
  name: 'Post',
  filePathPattern: 'posts/*.mdx',
  contentType: 'mdx',
  fields: {
    title: {
      type: 'string',
      description: 'The title of the post',
      required: true
    },
    description: {
      type: 'string',
      description: 'The description of the post',
      required: true
    },
    publishedOn: {
      type: 'date',
      description: 'The publishing date of the post',
      required: true
    },
    editedOn: {
      type: 'date',
      description: 'The editing date of the post',
      required: true
    },
    status: {
      type: 'enum',
      description: 'The status of the post',
      options: ['draft', 'published', 'edited'],
      required: true
    }
  },
  computedFields: {
    slug: {
      type: 'string',
      description: 'The slug of the post',
      resolve: (post) => post._raw.sourceFileName.replace(/\.mdx?$/, '')
    }
  }
}));

export default makeSource({
  contentDirPath: 'data',
  contentDirExclude: ['themes'],
  documentTypes: [Post]
});
```

**Comment by Xenfo** [comment]
I just ran a build on Vercel and it seems like there is no error there, not sure what's going on.

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide **minimal** a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by Xenfo** [comment]
https://github.com/Xenfo/cl-demo

**Comment by schickling** [comment]
I couldn't reproduce the problem you've described:

<img width="1204" alt="CleanShot 2023-06-28 at 17 30 26@2x" src="https://github.com/contentlayerdev/contentlayer/assets/1567498/5d06dfe2-203f-4702-a2db-a4c115bafc71">

**Comment by Xenfo** [comment]
Seems like something was deprecated on Node 19, and removed in Node 20, which is where the issue lies.
```
cl-demo on  main [!] via  v20.3.1 took 22s
❯ rtx use node@18
Downloading node-v18.16.1-linux-x64.tar.gz...
-> https://nodejs.org/dist/v18.16.1/node-v18.16.1-linux-x64.tar.gz
Installing node-v18.16.1-linux-x64...
Installed node-v18.16.1-linux-x64 to /home/xenfo/.local/share/rtx/installs/node/18.16.1
rtx node@18.16.1 9.5.1                                                                                             ✓ 15s
cl-demo on  main [!?] via  v18.16.1 took 15s
❯ npm i -g

cl-demo on  main [!?] via  v18.16.1
❯ node -v
v18.16.1

cl-demo on  main [!?] via  v18.16.1
❯ npm i -g yarn

added 1 package in 474ms
Reshimming rtx 18.16.1...

cl-demo on  main [!?] via  v18.16.1
❯ yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 217ms
➤ YN0000: ┌ Link step
➤ YN0008: │ esbuild@npm:0.17.19 must be rebuilt because its dependency tree changed
➤ YN0008: │ protobufjs@npm:7.2.3 must be rebuilt because its dependency tree changed
➤ YN0008: │ contentlayer@npm:0.3.3 must be rebuilt because its dependency tree changed
➤ YN0000: └ Completed in 1s 257ms
➤ YN0000: Done in 1s 650ms

cl-demo on  main [!?] via  v18.16.1 took 2s
❯ yarn contentlayer build
Generated 1 documents in .contentlayer

cl-demo on  main [!?] via  v18.16.1
❯ rtx use node@19
Downloading node-v19.9.0-linux-x64.tar.gz...
-> https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.gz
WARNING: node-v19.9.0-linux-x64 is in LTS Maintenance mode and nearing its end of life.
It only receives *critical* security updates, *critical* bug fixes and documentation updates.
Installing node-v19.9.0-linux-x64...
Installed node-v19.9.0-linux-x64 to /home/xenfo/.local/share/rtx/installs/node/19.9.0
rtx node@19.9.0 9.6.3                                                                                              ✓ 13s
cl-demo on  main [!?] via  v19.9.0 took 12s
❯ npm i -g yarn

added 1 package in 339ms
Reshimming rtx 19.9.0...

cl-demo on  main [!?] via  v19.9.0
❯ yarn contentlayer build
Generated 1 documents in .contentlayer
(node:115156) [DEP0164] DeprecationWarning: Implicit coercion to integer for exit code is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

cl-demo on  main [!?] via  v19.9.0
❯ rtx use node@20

cl-demo on  main [!?] via  v20.3.1
❯ yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0008: │ esbuild@npm:0.17.19 must be rebuilt because its dependency tree changed
➤ YN0008: │ protobufjs@npm:7.2.3 must be rebuilt because its dependency tree changed
➤ YN0008: │ contentlayer@npm:0.3.3 must be rebuilt because its dependency tree changed
➤ YN0000: └ Completed in 1s 27ms
➤ YN0000: Done in 1s 368ms

cl-demo on  main [!?] via  v20.3.1
❯ yarn contentlayer build
Generated 1 documents in .contentlayer
TypeError: The "code" argument must be of type number. Received an instance of Object
    at process.set [as exitCode] (node:internal/bootstrap/node:124:9)
    at Cli.runExit (/tmp/cl-demo/node_modules/clipanion/lib/advanced/Cli.js:232:26)
    at run (file:///tmp/cl-demo/node_modules/@contentlayer/cli/src/index.ts:39:3)
    at main (/tmp/cl-demo/node_modules/contentlayer/bin/cli.cjs:5:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}

cl-demo on  main [!?] via  v20.3.1
❯
```

```
(node:115156) [DEP0164] DeprecationWarning: Implicit coercion to integer for exit code is deprecated.
```

**Comment by schickling** [comment]
I still couldn't reproduce it via GitPod. 

<img width="410" alt="CleanShot 2023-06-29 at 09 34 22@2x" src="https://github.com/contentlayerdev/contentlayer/assets/1567498/5a459136-a3c0-46f8-b98b-42e8cf9c9089">

**Comment by Xenfo** [comment]
Just reproduced on GitPod too

![image](https://github.com/contentlayerdev/contentlayer/assets/46873232/66e7276c-de48-4f16-9e5d-eec1c3f39fef)

**Comment by Andrew-Sem** [comment]
@Xenfo, hey, did you solve this somehow?

**Comment by Xenfo** [comment]
> @Xenfo, hey, did you solve this somehow?

No, it’s annoying but I just let it happen since everything is still generated properly

**Comment by dstroot** [comment]
Same here - issue occuring on Node v20.5.0

**Comment by Slyracoon23** [comment]
I have the same issue Node v20.5.1

**Comment by YannHulot** [comment]
Same problem here. Not sure if there is anything to do about it.

**Comment by CodeSpent** [comment]
This is related to Node Deprecation [DEP0164 (process.exit(code), process.exitCode coercion to integer](https://nodejs.org/api/deprecations.html#DEP0164).

In relation to contentlayer, the CLI is attempting to assign a resulting object with `documentCount`'s existence as a means of coercing to a positive exit code. 

in CLI.js function `runExit`, assignment to `process.exitCode` should be a valid integer.

![image](https://github.com/contentlayerdev/contentlayer/assets/7674344/a9c59624-6949-41b4-af6d-b65f97c084d9)

It is worth noting that this doesn't effect functionality of CLI commands. It just impacts the ability for CLI commands to reporting a valid exit code, so it will always be assumed to be an error.

**Comment by gustaveWPM** [comment]
Hello, same problem here.
This error message is confusing: I thought I had done something wrong in my Contentlayer configuration file.

Thank you all for your investigations.

**Comment by andri2621** [comment]
> Hello, same problem here. This error message is confusing: I thought I had done something wrong in my Contentlayer configuration file.
> 
> Thank you all for your investigations.

Me too. I just upgrade my node to `v20.9.0`, and this happen.
I think i should downgrade again.

**Comment by gustaveWPM** [comment]
> > Hello, same problem here. This error message is confusing: I thought I had done something wrong in my Contentlayer configuration file.
> > Thank you all for your investigations.
> 
> Me too. I just upgrade my node to `v20.9.0`, and this happen. I think i should downgrade again.

No, don't worry.
Even if the error message occurs, the code runs...

It's just very confusing.

**Comment by jrolfs** [comment]
So it seems the **[`BuildCommand`](https://github.com/contentlayerdev/contentlayer/blob/2f491c540e1d3667577f57fa368b150bff427aaf/packages/%40contentlayer/cli/src/commands/BuildCommand.ts#L27)** [has been yielding](https://github.com/contentlayerdev/contentlayer/blob/2f491c540e1d3667577f57fa368b150bff427aaf/packages/%40contentlayer/cli/src/commands/BuildCommand.ts#L27) an object (of type [`GenerateInfo`](https://github.com/contentlayerdev/contentlayer/blob/2f491c540e1d3667577f57fa368b150bff427aaf/packages/%40contentlayer/core/src/generation/generate-dotpkg.ts#L48-L50)) to **clipanion**'s [`Cli#runExit`](https://mael.dev/clipanion/docs/api/cli#clirunexit) API which instead expects an exit code `number`.

I suspect this has gone unnoticed for so long due to the now [legacy `process.exitCode` coercion](https://nodejs.org/api/deprecations.html#DEP0164) behavior in **Node.js**. I will open a PR with my attempt at a fix, but I've also applied it as a patch via Yarn for now.

Here's what the patch looks like using [`yarn patch`](https://yarnpkg.com/features/patching):

**.yarn/patches/@contentlayer-cli-npm-0.3.3-e932de1bc4.patch**
```patch
diff --git a/dist/commands/BuildCommand.js b/dist/commands/BuildCommand.js
index 1cc67c8c9b28622c2391c1da70754ab99dcc35d6..27b35388b71bc8cb64463329e9b1ef251b3382b4 100644
--- a/dist/commands/BuildCommand.js
+++ b/dist/commands/BuildCommand.js
@@ -4,7 +4,7 @@ import { BaseCommand } from './_BaseCommand.js';
 class BuildCommand extends BaseCommand {
     constructor() {
         super(...arguments);
-        this.executeSafe = () => pipe(this.clearCacheIfNeeded(), T.chain(() => core.getConfig({ configPath: this.configPath })), T.tap((config) => (config.source.options.disableImportAliasWarning ? T.unit : T.fork(core.validateTsconfig))), T.chain((config) => core.generateDotpkg({ config, verbose: this.verbose })), T.tap(core.logGenerateInfo), OT.withSpan('@contentlayer/cli/commands/BuildCommand:executeSafe'));
+        this.executeSafe = () => pipe(this.clearCacheIfNeeded(), T.chain(() => core.getConfig({ configPath: this.configPath })), T.tap((config) => (config.source.options.disableImportAliasWarning ? T.unit : T.fork(core.validateTsconfig))), T.chain((config) => core.generateDotpkg({ config, verbose: this.verbose })), T.tap(core.logGenerateInfo), T.map(() => 0), OT.withSpan('@contentlayer/cli/commands/BuildCommand:executeSafe'));
     }
 }
 BuildCommand.paths = [['build']];
```

**Comment by imadbz** [comment]
still getting this error
+1

**Comment by MildTomato** [comment]
also just got this error 
+1

**Comment by zce** [comment]
https://github.com/contentlayerdev/contentlayer/issues/429#issuecomment-1974928678

**Comment by psr-ai** [comment]
Issue goes away on node version 18

**Comment by jrolfs** [comment]
In case y'all missed it, the official recommendation from those working with @schickling to keep this project going is to temporarily switch to the **[contentlayer2](https://github.com/timlrx/contentlayer2)** fork while they sort out the longer-term plan for continued support of this project.

My fix for this issue was [merged](https://github.com/timlrx/contentlayer2/pull/8) over there and released in **[0.4.5](https://github.com/timlrx/contentlayer2/releases/tag/v0.4.5)** on the fork.

See:
- https://github.com/contentlayerdev/contentlayer/issues/429#issuecomment-2030339798
- https://github.com/contentlayerdev/contentlayer/issues/651#issue-2186932012

Follow:
- https://github.com/contentlayerdev/contentlayer/issues/429
- https://github.com/contentlayerdev/contentlayer/issues/651

I wrote some documentation to help anyone else moving over to the fork here: https://github.com/timlrx/contentlayer2/pull/18

**Comment by nmn** [comment]
Getting the same error in Bun and Node 22.

I think I found the root cause for the bug. It's in `clipanion` package. Here's the patch that fixed the problem for me:

```patch
diff --git a/lib/advanced/Cli.js b/lib/advanced/Cli.js
index b6946ca4ac6b2dd5d78598dfdef6caca7fcf5e33..41f84c271122007e819188bc0c8e0253069328ac 100644
--- a/lib/advanced/Cli.js
+++ b/lib/advanced/Cli.js
@@ -220,7 +220,7 @@ class Cli {
             : noopCaptureActivator;
         let exitCode;
         try {
-            exitCode = await activate(() => command.validateAndExecute().catch(error => command.catch(error).then(() => 0)));
+            exitCode = await activate(() => command.validateAndExecute().catch(error => command.catch(error)).then(() => 0));
         }
         catch (error) {
             context.stdout.write(this.error(error, { colored, command }));

```

Without the patch, `exitCode` is being set to `{ documentCount: 0 }` which is an object and thus causing the bug.

**Comment by scshiv29-dev** [comment]
@nmn  is there a solution  for this even I am getting this error in Bun and Node 22.

**Comment by nmn** [comment]
@scshiv29-dev I literally shared my solution. I used `bun`, use that or `patch-package` to patch the `clipanion` package and move that one closing paren `)` as I showed in my diff above.

**Comment by scshiv29-dev** [comment]
@nmn  yea I was not familiar with package patching and so I asked . I shifted to contentlayer2 .
