### ISSUE TITLE
error remarkGfm in contentlayer

### ISSUE THREAD

**Issue by levanthoi** [contentlayerdev/contentlayer#560]
File updated: blog-test-2/index.mdx
X [ERROR] TypeError: Cannot read properties of undefined (reading 'inTable')
    at Object.exitCodeText (file:///D:/nextjs/portfolio/node_modules/mdast-util-gfm-table/lib/index.js:123:17)
    at compile (file:///D:/nextjs/portfolio/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
    at fromMarkdown (file:///D:/nextjs/portfolio/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:187:29)      
    at parser (file:///D:/nextjs/portfolio/node_modules/remark-parse/lib/index.js:18:12)
    at Function.parse (file:///D:/nextjs/portfolio/node_modules/unified/lib/index.js:273:12)
    at executor (file:///D:/nextjs/portfolio/node_modules/unified/lib/index.js:393:31)
    at new Promise (<anonymous>)
    at Function.process (file:///D:/nextjs/portfolio/node_modules/unified/lib/index.js:380:14)
    at process (file:///D:/nextjs/portfolio/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:50:22)
    at onload (file:///D:/nextjs/portfolio/node_modules/@mdx-js/esbuild/lib/index.js:151:22) [plugin @mdx-js/esbuild]

    _mdx_bundler_entry_point-31de6c00-dcdc-4dbf-8c36-c6a5d6276227.mdx:0:0:
      0 │ ---
        ╵ ^

Error: Found 1 problems in 1 documents.

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.

     • "blog-test-2/index.mdx": UnexpectedMDXError: Error: Build failed with 1 error:
     _mdx_bundler_entry_point-31de6c00-dcdc-4dbf-8c36-c6a5d6276227.mdx:0:0: ERROR: [plugin: @mdx-js/esbuild] TypeError: Cannot read properties of undefined (reading 'inTable')
         at Object.exitCodeText (file:///D:/nextjs/portfolio/node_modules/mdast-util-gfm-table/lib/index.js:123:17)
         at compile (file:///D:/nextjs/portfolio/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:352:40)      
         at fromMarkdown (file:///D:/nextjs/portfolio/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:187:29) 
         at parser (file:///D:/nextjs/portfolio/node_modules/remark-parse/lib/index.js:18:12)
         at Function.parse (file:///D:/nextjs/portfolio/node_modules/unified/lib/index.js:273:12)
         at executor (file:///D:/nextjs/portfolio/node_modules/unified/lib/index.js:393:31)
         at new Promise (<anonymous>)
         at Function.process (file:///D:/nextjs/portfolio/node_modules/unified/lib/index.js:380:14)
         at process (file:///D:/nextjs/portfolio/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:50:22)
         at onload (file:///D:/nextjs/portfolio/node_modules/@mdx-js/esbuild/lib/index.js:151:22)

SourceFetchDataError: {
  "_tag": "HandledFetchDataError"
}

**Comment by jibone** [comment]
I am currently facing the same problem, I think this issue is discussing it https://github.com/contentlayerdev/contentlayer/issues/558

**Comment by Seokho0120** [comment]
me too...😢
