### ISSUE TITLE
@vercel/postgres client undefined when next config exported with contentlayer

### ISSUE THREAD

**Issue by tomheaton** [contentlayerdev/contentlayer#561]
simple nextjs 13 app dir typescript project using pnpm workspaces, exporting next config using `withContentlayer` from `next-contentlayer`, attempting to use `sql` from `@vercel/postgres` throws error

```bash
 ⨯ ..\node_modules\.pnpm\@neondatabase+serverless@0.6.0\node_modules\@neondatabase\serverless\index.mjs (4:22) @ mod
 ⨯ TypeError: Cannot read properties of undefined (reading 'Client')
    at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/@neondatabase+serverless@0.6.0/node_modules/@neondatabase/serverless/index.mjs:20:65)
    at Module.(rsc)/../../node_modules/.pnpm/@neondatabase+serverless@0.6.0/node_modules/@neondatabase/serverless/index.mjs (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\vendor-chunks\@neondatabase+serverless@0.6.0.js:30:1)
    at __webpack_require__ (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/@vercel+postgres@0.5.0/node_modules/@vercel/postgres/dist/chunk-VGUHM5WG.js:11:82)
    at Module.(rsc)/../../node_modules/.pnpm/@vercel+postgres@0.5.0/node_modules/@vercel/postgres/dist/chunk-VGUHM5WG.js (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\vendor-chunks\@vercel+postgres@0.5.0.js:20:1)
    at __webpack_require__ (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/@vercel+postgres@0.5.0/node_modules/@vercel/postgres/dist/index-node.js:11:76)
    at Module.(rsc)/../../node_modules/.pnpm/@vercel+postgres@0.5.0/node_modules/@vercel/postgres/dist/index-node.js (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\vendor-chunks\@vercel+postgres@0.5.0.js:30:1)
    at __webpack_require__ (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/api/waitlist/create/route.ts:5:74)
    at Module.(rsc)/./src/app/api/waitlist/create/route.ts (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\app\api\waitlist\create\route.js:172:1)
    at __webpack_require__ (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/next@13.5.3_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fwaitlist%2Fcreate%2Froute&page=%2Fapi%2Fwaitlist%2Fcreate%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fwaitlist%2Fcreate%2Froute.ts&appDir=C%3A%5CUsers%5Cthoma%5CWebstormProjects%5Ckampeign%5Capps%5Cweb%5Csrc%5Capp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=C%3A%5CUsers%5Cthoma%5CWebstormProjects%5Ckampeign%5Capps%5Cweb&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!:16:143)
    at Module.(rsc)/../../node_modules/.pnpm/next@13.5.3_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fwaitlist%2Fcreate%2Froute&page=%2Fapi%2Fwaitlist%2Fcreate%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fwaitlist%2Fcreate%2Froute.ts&appDir=C%3A%5CUsers%5Cthoma%5CWebstormProjects%5Ckampeign%5Capps%5Cweb%5Csrc%5Capp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=C%3A%5CUsers%5Cthoma%5CWebstormProjects%5Ckampeign%5Capps%5Cweb&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D! (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\app\api\waitlist\create\route.js:162:1)
    at __webpack_require__ (C:\Users\tomheaton\dev\my-project\apps\web\.next\server\webpack-runtime.js:33:43) {
  page: '/api/waitlist/create'
}
```

```json
"@vercel/postgres": "^0.5.0",
"contentlayer": "^0.3.4",
"next": "^13.5.3",
"next-contentlayer": "^0.3.4",
"react": "18.2.0",
"react-dom": "18.2.0",
```

tested on both windows and macos

matching issue: [vercel/storage#416](https://github.com/vercel/storage/issues/416)

**Comment by z4nr34l** [comment]
I've migrated out from contentlayer due to missing compatibility for Next 14 and latest opentelemetry :D

**Comment by joulev** [comment]
https://github.com/contentlayerdev/contentlayer/blob/2f491c540e1d3667577f57fa368b150bff427aaf/packages/next-contentlayer/src/index.ts#L45-L53

These are the offending lines, which caused the error above when used with `@neondatabase/serverless` (which `@vercel/postgres` uses). This is a bug in `@neondatabase/serverless` (I opened the ticket in https://github.com/neondatabase/serverless/issues/54), but since https://github.com/vercel/next.js/pull/58967 is already merged these hack lines are no longer necessary so it's good to remove them.
