### ISSUE TITLE
Can not setup contentlayer with a very minimal next.config.js

### ISSUE THREAD

**Issue by krachtstefan** [contentlayerdev/contentlayer#57]
After having trouble installing contentlayer on my nextjs site, I tried it on a bare new project and still run into the same error. I hope I don't miss anything, but I always end with the following error

```javascript
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
/Users/sk/Desktop/nextjs-blog/node_modules/next-contentlayer/dist/index-cjs.cjs:23
                return nextConfig.redirects?.() ?? [];
                                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/sk/Desktop/nextjs-blog/next.config.js:1:30)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

## Stepts to reproduce ([example repo](https://github.com/krachtstefan/contentlayer-bugreport)): 

- created a brand new project via
`npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"`
- installed contentlayer via `npm install contentlayer next-contentlayer`
- `npm run dev` sucessfully starts the server until this step
- added a `next.config.js` file with the following content:
   ```javascript
   const { withContentlayer } = require("next-contentlayer");
   module.exports = withContentlayer()({});
   ```
- `npm run dev` crashes with the error above

Thanks for creating this repo, can't wait to try it out!

**Comment by schickling** [comment]
Which Node.js version are you using? Contentlayer requires 14+.

**Comment by krachtstefan** [comment]
Wow, that was easy! Thanks for the quick reply!
