### ISSUE TITLE
Getting this error when deploying to vercel

### ISSUE THREAD

**Issue by OhYello** [contentlayerdev/contentlayer#570]
```
"dependencies": {
    "@fontsource-variable/inter": "^5.0.13",
    "@heroicons/react": "^2.0.18",
    "@tailwindcss/line-clamp": "^0.4.4",
    "@types/node": "20.8.7",
    "@vercel/analytics": "^1.1.1",
    "autoprefixer": "10.4.16",
    "clsx": "^2.0.0",
    "contentlayer": "^0.3.4",
    "esbuild": "^0.19.5",
    "eslint": "8.51.0",
    "eslint-config-next": "^13.5.6",
    "framer-motion": "^10.16.4",
    "image-size": "^1.0.2",
    "mdast-util-toc": "^7.0.0",
    "mdx-bundler": "^9.2.1",
    "next": "13.5.6",
    "next-contentlayer": "^0.3.4",
    "next-themes": "^0.2.1",
    "postcss": "8.4.31",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-masonry-css": "^1.0.16",
    "rehype-autolink-headings": "^7.0.0",
    "rehype-prism-plus": "^1.6.3",
    "rehype-slug": "^6.0.0",
    "remark": "^15.0.1",
    "remark-gfm": "^4.0.0",
    "tailwind-merge": "^1.14.0",
    "tailwindcss": "3.3.3",
    "typescript": "5.2.2"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.10",
    "@types/js-yaml": "^4.0.8",
    "@types/react": "^18.2.29",
    "@types/react-dom": "^18.2.14",
    "@typescript-eslint/eslint-plugin": "^6.8.0",
    "@typescript-eslint/parser": "^6.8.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.1",
    "prettier": "^3.0.3",
    "prettier-plugin-tailwindcss": "^0.5.6"
  }
 ```

```
✘ [ERROR] TypeError: Cannot read properties of undefined (reading 'inTable')
--
00:52:26.223 | at Object.exitCodeText (file:///vercel/path0/node_modules/mdast-util-gfm-table/lib/index.js:123:17)
00:52:26.223 | at compile (file:///vercel/path0/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
00:52:26.223 | at fromMarkdown (file:///vercel/path0/node_modules/mdast-util-from-markdown/lib/index.js:187:29)
00:52:26.223 | at parser (file:///vercel/path0/node_modules/remark-parse/lib/index.js:18:12)
00:52:26.223 | at Function.parse (file:///vercel/path0/node_modules/unified/lib/index.js:273:12)
00:52:26.224 | at executor (file:///vercel/path0/node_modules/unified/lib/index.js:393:31)
00:52:26.224 | at new Promise (<anonymous>)
00:52:26.224 | at Function.process (file:///vercel/path0/node_modules/unified/lib/index.js:380:14)
00:52:26.224 | at process (file:///vercel/path0/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:50:22)
00:52:26.224 | at onload (file:///vercel/path0/node_modules/@mdx-js/esbuild/lib/index.js:151:22) [plugin @mdx-js/esbuild]
00:52:26.224 |  
00:52:26.224 | _mdx_bundler_entry_point-53986e5e-00df-4084-8275-8950192a8782.mdx:0:0:
00:52:26.224 | 0 │ ---
00:52:26.224 | ╵ ^
00:52:26.224 |  
00:52:26.235 | ✘ [ERROR] TypeError: Cannot read properties of undefined (reading 'inTable')
00:52:26.235 | at Object.exitCodeText (file:///vercel/path0/node_modules/mdast-util-gfm-table/lib/index.js:123:17)
00:52:26.235 | at compile (file:///vercel/path0/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
00:52:26.235 | at fromMarkdown (file:///vercel/path0/node_modules/mdast-util-from-markdown/lib/index.js:187:29)
00:52:26.235 | at parser (file:///vercel/path0/node_modules/remark-parse/lib/index.js:18:12)
00:52:26.235 | at Function.parse (file:///vercel/path0/node_modules/unified/lib/index.js:273:12)
00:52:26.235 | at executor (file:///vercel/path0/node_modules/unified/lib/index.js:393:31)
00:52:26.235 | at new Promise (<anonymous>)
00:52:26.235 | at Function.process (file:///vercel/path0/node_modules/unified/lib/index.js:380:14)
00:52:26.236 | at process (file:///vercel/path0/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:50:22)
00:52:26.236 | at onload (file:///vercel/path0/node_modules/@mdx-js/esbuild/lib/index.js:151:22) [plugin @mdx-js/esbuild]
00:52:26.236 |  
00:52:26.236 | _mdx_bundler_entry_point-c39f372a-23b0-44db-9910-338353d68817.mdx:0:0:
00:52:26.236 | 0 │ ---
00:52:26.236 | ╵ ^
00:52:26.236 |  
00:52:26.683 | ✘ [ERROR] TypeError: Cannot read properties of undefined (reading 'inTable')
00:52:26.683 | at Object.exitCodeText (file:///vercel/path0/node_modules/mdast-util-gfm-table/lib/index.js:123:17)
00:52:26.683 | at compile (file:///vercel/path0/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
00:52:26.683 | at fromMarkdown (file:///vercel/path0/node_modules/mdast-util-from-markdown/lib/index.js:187:29)
00:52:26.683 | at parser (file:///vercel/path0/node_modules/remark-parse/lib/index.js:18:12)
00:52:26.683 | at Function.parse (file:///vercel/path0/node_modules/unified/lib/index.js:273:12)
00:52:26.683 | at executor (file:///vercel/path0/node_modules/unified/lib/index.js:393:31)
00:52:26.683 | at new Promise (<anonymous>)
00:52:26.683 | at Function.process (file:///vercel/path0/node_modules/unified/lib/index.js:380:14)
00:52:26.683 | at process (file:///vercel/path0/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:50:22)
00:52:26.683 | at onload (file:///vercel/path0/node_modules/@mdx-js/esbuild/lib/index.js:151:22) [plugin @mdx-js/esbuild]
00:52:26.683 |  
00:52:26.684 | _mdx_bundler_entry_point-291974ba-9185-49cb-acb5-f3cd251b51e7.mdx:0:0:
00:52:26.684 | 0 │ ---
00:52:26.684 | ╵ ^
00:52:26.684 |  
00:52:26.706 | Error: Found 3 problems in 15 documents.
00:52:26.706 |  
00:52:26.706 | └── Encountered unexpected errors while processing of 3 documents. This is possibly a bug in Contentlayer. Please open an issue.
```

**Comment by tatop** [comment]
I think remark-gfm, try using the 3.0.1 version. The 4.0 doesn't work.

**Comment by Leehyunji0715** [comment]
> I think it's remark-gfm, try using the 3.0.1 version. The 4.0 doesn't work.

you saved my day, thanks!
