### ISSUE TITLE
%2F in Path while building to production 

### ISSUE THREAD

**Issue by NoneWofie** [contentlayerdev/contentlayer#578]
Hi, 

I've completed my project and everything works fine while running `npm run dev` (I'm using Next13 with app router). However, when I try to build it, I'm having errors where it can't find the correct URI path of my slugs. 

**This is the error:**
```
next build

Generated 1 documents in .contentlayer
...
 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/8)  
Error: Post not found for slug: blogs%2FMinutes-Writing-101
    at __WEBPACK_DEFAULT_EXPORT__ (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/.next/server/app/blogs/[slug]/page.js:1:2577)
    at ev (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:11059)
    at /Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:21907
    at Array.toJSON (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:25224)
    at stringify (<anonymous>)
    at eT (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:13686)
    at eP (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:14212)
    at Timeout._onTimeout (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:12034)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Error: Blog not found for slug: blogs%2FMinutes-Writing-101
    at Module.generateMetadata (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/.next/server/app/blogs/[slug]/page.js:1:2397)
    at /Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:107:40343
    at /Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/@opentelemetry+api@1.6.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/@opentelemetry+api@1.6.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at NoopTracer.startActiveSpan (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/@opentelemetry+api@1.6.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
    at ProxyTracer.startActiveSpan (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/@opentelemetry+api@1.6.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
    at /Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:106:107
    at NoopContextManager.with (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/@opentelemetry+api@1.6.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/@opentelemetry+api@1.6.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)

Error occurred prerendering page "/blogs/blogs%2FMinutes-Writing-101". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Post not found for slug: blogs%2FMinutes-Writing-101
    at __WEBPACK_DEFAULT_EXPORT__ (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/.next/server/app/blogs/[slug]/page.js:1:2577)
    at ev (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:11059)
    at /Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:21907
    at Array.toJSON (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:25224)
    at stringify (<anonymous>)
    at eT (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:13686)
    at eP (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:14212)
    at Timeout._onTimeout (/Users/reuben/Desktop/github/Portfolio-v2/my-portfolio/node_modules/.pnpm/next@13.5.4_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:12034)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
 ✓ Generating static pages (8/8)

> Export encountered errors on following paths:
	/blogs/[slug]/page: /blogs/blogs%2FMinutes-Writing-101
	/page: /
```

I believe the error is due to the path containing `%2F`. 

**This is my contentlayer.config.ts file**
```ts
import { defineDocumentType, makeSource } from "contentlayer/source-files";

// Plugins
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import rehypePrettyCode from "rehype-pretty-code";
import rehypeSlug from "rehype-slug";
import remarkGfm from "remark-gfm";
import remarkToc from "remark-toc";
import remarkHtml from "remark-html";
import remarkParse from "remark-parse";
import rehypeParse from "rehype-parse";
import rehypeStringify from "rehype-stringify";
import remarkRehype from "remark-rehype";
import remarkNormalizeHeadings from "remark-normalize-headings";

// Types
import { type Options as RehypePrettyCodeOptions } from "rehype-pretty-code";
import remarkBreaks from "remark-breaks";

export const Projects = defineDocumentType(() => ({
	name: "Projects",
	filePathPattern: "projects/**/*.mdx",
	contentType: "mdx",
	fields: {
		title: {
			type: "string",
			required: true,
		},
		date: {
			type: "date",
			required: true,
		},
		category: {
			type: "enum",
			options: ["personal", "work"],
			required: true,
		},
		tags: {
			type: "list",
			of: { type: "string" },
			required: true,
		},
		image: {
			type: "string",
			required: true,
		},
	},
	computedFields: {
		url: {
			type: "string",
			resolve: doc => `/${doc._raw.flattenedPath}`,
		},
	},
}));

export const Blogs = defineDocumentType(() => ({
	name: "Blogs",
	filePathPattern: "blogs/**/*.mdx",
	contentType: "mdx",
	fields: {
		title: {
			type: "string",
			required: true,
		},
		date: {
			type: "date",
			required: true,
		},
		image: {
			type: "string",
			required: true,
		},
		tags: {
			type: "list",
			of: { type: "string" },
			required: true,
		},
	},
	computedFields: {
		url: {
			type: "string",
			resolve: doc => `/${doc._raw.flattenedPath}`,
		},
	},
}));

// Plugins config
const rehypeoptions: RehypePrettyCodeOptions = {
	// Use one of Shiki's packaged themes
	theme: "material-theme-lighter",
	// Set to true to keep the background color
	keepBackground: true,
	onVisitLine(node) {
		``;
		if (node.children.length === 0) {
			node.children = [{ type: "text", value: " " }];
		}
	},
	onVisitHighlightedLine(node) {
		if (node.properties.className) {
			node.properties.className!.push("highlighted");
		} else {
			node.properties.className = ["highlighted"];
		}
	},
	onVisitHighlightedChars(node: any, id: any) {
		if (node.properties.className) {
			node.properties.className = ["word"];
		} else {
			node.properties.className.push("word");
		}
	},
};

export default makeSource({
	contentDirPath: "src/content",
	documentTypes: [Projects, Blogs],
	mdx: {
		remarkPlugins: [
			//@ts-ignore
			remarkBreaks,
			//@ts-ignore
			remarkNormalizeHeadings,
			[
				remarkToc,
				{
					heading: "Table of Contents",
				},
			],
		],
		rehypePlugins: [
			//@ts-ignore
			[rehypeParse, { fragment: true }],
			//@ts-ignore
			[rehypePrettyCode, rehypeoptions],
			rehypeSlug,
			[
				rehypeAutolinkHeadings,
				{
					properties: {
						ariaLabel: "Link to section",
						className:
							"font-bold no-underline hover:text-gray-700 hover:underline",
					},
					behavior: "wrap",
				},
			],
			//@ts-ignore
			rehypeStringify,
		],
	},
});
```

**My src project directory:**
<img width="332" alt="image" src="https://github.com/contentlayerdev/contentlayer/assets/70955773/d94d9bfb-c32c-4968-bb42-5f90e6a99f79">

**package.json file:**
```json
{
	"name": "my-portfolio",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"dev": "next dev",
		"build": "next build",
		"start": "next start",
		"lint": "next lint"
	},
	"dependencies": {
		"@react-three/fiber": "^8.14.5",
		"@types/three": "^0.157.0",
		"contentlayer": "^0.3.4",
		"date-fns": "^2.30.0",
		"maath": "^0.10.4",
		"mathjax": "^3.2.2",
		"next": "13.5.4",
		"next-contentlayer": "^0.3.4",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"rehype-autolink-headings": "^7.0.0",
		"rehype-parse": "^9.0.0",
		"rehype-pretty-code": "^0.10.1",
		"rehype-slug": "^6.0.0",
		"rehype-stringify": "^10.0.0",
		"remark-breaks": "^4.0.0",
		"remark-gfm": "^4.0.0",
		"remark-html": "^16.0.1",
		"remark-normalize-headings": "^4.0.0",
		"remark-parse": "^11.0.0",
		"remark-rehype": "^11.0.0",
		"remark-toc": "^9.0.0",
		"shiki": "^0.14.5",
		"three": "^0.157.0",
		"zustand": "^4.4.3"
	},
	"devDependencies": {
		"@tailwindcss/typography": "^0.5.10",
		"@types/mdx": "^2.0.9",
		"@types/node": "^20",
		"@types/react": "^18",
		"@types/react-dom": "^18",
		"autoprefixer": "^10",
		"daisyui": "^3.9.2",
		"eslint": "^8",
		"eslint-config-next": "13.5.4",
		"postcss": "^8",
		"tailwindcss": "^3",
		"typescript": "^5"
	}
}
```

Please help

**Comment by linus-jansson** [comment]
I had a lot of problems while settings this up and remembered this issue when I solved everything here is what I found from the example

For context here is my config
```ts
// contentlayer.config.ts
import { defineDocumentType, makeSource } from 'contentlayer/source-files'

export const Post = defineDocumentType(() => ({
  name: 'Post',
  filePathPattern: `posts/**/*.md`,
  fields: {
    title: { type: 'string', required: true },
    date: { type: 'date', required: true },
  },
  computedFields: {
    url: { type: 'string', resolve: (post) => `posts/${post._raw.sourceFileName}` },
  },
}))

export default makeSource({ contentDirPath: 'data', documentTypes: [Post] })
```
 and here is my wanted file structure:
<img width="249" alt="image" src="https://github.com/contentlayerdev/contentlayer/assets/30862662/0c6e3493-1ae9-4cdc-998c-563bb64cdda0">

Here is my orginally modified `[slug]/page.tsx`
```tsx
// app/posts/[slug]/page.tsx
import { format, parseISO } from "date-fns"
import { allPosts } from "contentlayer/generated"

export const generateStaticParams = async () =>
    allPosts.map((post) => ({ slug: post._raw.flattenedPath }))

const getPost = (slug: string) => {
    const post = allPosts.find((post) => post._raw.flattenedPath === slug)
    if (!post) throw new Error(`Post not found for slug: ${slug}`)
    return post
}

export const generateMetadata = ({ params }: { params: { slug: string } }) => {
    const post = getPost(params.slug)
    return { title: post.title }
}

const PostLayout = ({ params }: { params: { slug: string } }) => {
    const post = getPost(params.slug)

    return (
        <article className="mx-auto max-w-xl py-8 bg-white">
            <div className="mb-8 text-center">
                <time
                    dateTime={post.date}
                    className="mb-1 text-xs text-gray-600"
                >
                    {format(parseISO(post.date), "LLLL d, yyyy")}
                </time>
                <h1 className="text-3xl font-bold">{post.title}</h1>
            </div>
            <div
                className="[&>*]:mb-3 [&>*:last-child]:mb-0"
                dangerouslySetInnerHTML={{ __html: post.body.html }}
            />
        </article>
    )
}

export default PostLayout
```

Only actual difference between the getting started example in the docs and my code, is the file structure and my `getPost()` function

**aswell as you have, I have a nested content (eg /content/posts/post-01.md) folder which for some reason does't work because `flattendPath !== slug`. So I changed flattendPath everywhere to `sourceFileName`**

**Here is my new `getPost()` function.**
```ts
const getPost = (slug: string) => {
    const post = allPosts.find((post) => post._raw.sourceFileName === slug)
    if (!post) throw new Error(`Post not found for slug: ${slug}`)
    return post
}
```
**This is working in dev but not while building, that is becuase it can't generate the pages due to that there is a generateStaticParams aswell. Changing `flattendPath` in that funciton to `sourceFileName` works.** LMK if that solves your problem!

Maybe I didn't read the right docs while setting up the project but I taught it was a bit lacking. Would be great to have all the `_raw` properties meaning documented.

**Comment by paulcjy** [comment]
If it works well without `%2F`, try this to find post.
```ts
const post = allPosts.find((post) => post.whateverYouSet === decodeURIComponent(params.slug) )
```

**Comment by NoneWofie** [comment]
@linus-jansson It works! thank you.
