### ISSUE TITLE
@esbuild/linux-x64

### ISSUE THREAD

**Issue by hff399** [contentlayerdev/contentlayer#613]
[19:22:19.135] Running build in Washington, D.C., USA (East) – iad1
[19:22:19.251] Cloning github.com/hff399/formify (Branch: main, Commit: 3dfbfdc)
[19:22:20.155] Cloning completed: 903.308ms
[19:22:20.155] Running "if [ "$VERCEL_ENV" == "production" ]; then exit 1; else exit 0; fi"
[19:22:29.340] Restored build cache
[19:22:29.421] Running "vercel build"
[19:22:30.133] Vercel CLI 32.6.1
[19:22:30.593] Installing dependencies...
[19:22:42.883] 
[19:22:42.884] > formify@0.0.1 prepare
[19:22:42.884] > cd .. && husky install user-public/.husky
[19:22:42.885] 
[19:22:42.945] fatal: not a git repository (or any of the parent directories): .git
[19:22:42.948] husky - git command not found, skipping install
[19:22:42.981] 
[19:22:42.982] added 257 packages, removed 1 package, and changed 12 packages in 12s
[19:22:42.982] 
[19:22:42.982] 353 packages are looking for funding
[19:22:42.982]   run `npm fund` for details
[19:22:43.015] Detected Next.js version: 13.4.19
[19:22:43.031] Detected `package-lock.json` generated by npm 7+
[19:22:43.031] Running "npm run build"
[19:22:44.071] 
[19:22:44.071] > formify@0.0.1 build
[19:22:44.071] > next build
[19:22:44.071] 
[19:22:45.131] - warn You have enabled experimental features (serverActions, serverComponentsExternalPackages) in next.config.js.
[19:22:45.132] - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[19:22:45.133] 
[19:22:45.232] - info Creating an optimized production build...
[19:22:45.883] - info (pwa) Compiling for client (static)...
[19:22:45.884] - info (pwa) Service worker: /vercel/path0/public/sw.js
[19:22:45.884] - info (pwa)   URL: /sw.js
[19:22:45.885] - info (pwa)   Scope: /
[19:22:45.890] - info (pwa) Compiling for server...
[19:22:45.920] - info (pwa) Compiling for server...
[19:22:47.512] This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
[19:22:47.512] https://github.com/contentlayerdev/contentlayer/issues
[19:22:47.512] 
[19:22:47.512] An unchecked error was produced.
[19:22:47.512] 
[19:22:47.512] Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
[19:22:47.512] 
[19:22:47.513] If you are installing esbuild with npm, make sure that you don't specify the
[19:22:47.513] "--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
[19:22:47.513] of "package.json" is used by esbuild to install the correct binary executable
[19:22:47.513] for your current platform.
[19:22:47.513]     at generateBinPath (/vercel/path0/node_modules/esbuild/lib/main.js:1899:15)
[19:22:47.514]     at esbuildCommandAndArgs (/vercel/path0/node_modules/esbuild/lib/main.js:1969:33)
[19:22:47.514]     at ensureServiceIsRunning (/vercel/path0/node_modules/esbuild/lib/main.js:2133:25)
[19:22:47.517]     at Module.context (/vercel/path0/node_modules/esbuild/lib/main.js:2026:33)
[19:22:47.517]     at T.tryCatchPromise.UnknownEsbuildError.error.error (file:///vercel/path0/node_modules/@contentlayer/core/dist/getConfig/esbuild.js:64:79)
[19:22:47.517]     at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Effect/promise.mjs:13:5
[19:22:47.517]     at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Effect/effectAsync.mjs:30:5
[19:22:47.517]     at FiberContext.evaluateNow (file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:892:35)
[19:22:47.517]     at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:504:33
[19:22:47.517]     at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Support/Scheduler/index.mjs:11:22
[19:22:47.517] 
[19:22:47.517] Fiber: #0 (started at: 2023-12-09T16:22:47.466Z) was supposed to continue to: <empty trace>
[19:22:47.523] 
[19:22:47.523] Fiber: #0 (started at: 2023-12-09T16:22:47.466Z) Execution trace: <empty trace>
[19:22:47.523] 
[19:22:47.523] Fiber: #0 (started at: 2023-12-09T16:22:47.466Z) was spawned by: <empty trace>
[19:22:47.527] 
[19:22:47.527] OS: linux 5.10.174 (arch: x64)
[19:22:47.527] Process: /node18/bin/node /vercel/path0/node_modules/.bin/next build
[19:22:47.528] Node version: v18.18.0
[19:22:47.528] Contentlayer version: 0.3.4
[19:22:47.528] 
[19:22:47.608] Error: Command "npm run build" exited with 1
[19:22:49.207]

**Comment by hff399** [comment]
After redeploy all is okay.

**Comment by sanchezfdezjavier** [comment]
I'm experiencing the same issue. Working locally, breaking on first deploy, working after redeploy and breaking when I merge the PR into main. Happy to help reproducing!

Here's the logs that I'm getting:
```logs
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
--
17:47:31.816 | https://github.com/contentlayerdev/contentlayer/issues
17:47:31.816 |  
17:47:31.816 | An unchecked error was produced.
17:47:31.816 |  
17:47:31.817 | Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
17:47:31.817 |  
17:47:31.817 | If you are installing esbuild with npm, make sure that you don't specify the
17:47:31.817 | "--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
17:47:31.817 | of "package.json" is used by esbuild to install the correct binary executable
17:47:31.817 | for your current platform.
17:47:31.817 | at generateBinPath (/vercel/path0/node_modules/esbuild/lib/main.js:1899:15)
17:47:31.817 | at esbuildCommandAndArgs (/vercel/path0/node_modules/esbuild/lib/main.js:1969:33)
17:47:31.817 | at ensureServiceIsRunning (/vercel/path0/node_modules/esbuild/lib/main.js:2133:25)
17:47:31.817 | at Module.context (/vercel/path0/node_modules/esbuild/lib/main.js:2026:33)
17:47:31.817 | at T.tryCatchPromise.UnknownEsbuildError.error.error (file:///vercel/path0/node_modules/@contentlayer/core/dist/getConfig/esbuild.js:64:79)
17:47:31.817 | at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Effect/promise.mjs:13:5
17:47:31.818 | at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Effect/effectAsync.mjs:30:5
17:47:31.818 | at FiberContext.evaluateNow (file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:892:35)
17:47:31.818 | at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:504:33
17:47:31.818 | at file:///vercel/path0/node_modules/@effect-ts/system/_mjs/Support/Scheduler/index.mjs:11:22
17:47:31.818 |  
17:47:31.818 | Fiber: #0 (started at: 2024-02-04T16:47:31.776Z) was supposed to continue to: <empty trace>
17:47:31.818 |  
17:47:31.818 | Fiber: #0 (started at: 2024-02-04T16:47:31.776Z) Execution trace: <empty trace>
17:47:31.818 |  
17:47:31.818 | Fiber: #0 (started at: 2024-02-04T16:47:31.776Z) was spawned by: <empty trace>
17:47:31.819 |  
17:47:31.819 | OS: linux 5.10.174 (arch: x64)
17:47:31.819 | Process: /node18/bin/node /vercel/path0/node_modules/.bin/next build
17:47:31.819 | Node version: v18.18.2
17:47:31.820 | Contentlayer version: 0.3.4
17:47:31.820 |  
17:47:31.843 | Error: Command "npm run build" exited with 1
```

**Comment by sanchezfdezjavier** [comment]
> After redeploy all is okay.

Same, but after merging into main fails again for me :(
