### ISSUE TITLE
I can't use remark-directive in my project based on next.js

### ISSUE THREAD

**Issue by Alndaly** [contentlayerdev/contentlayer#640]
# My Code

```ts
// contentlayer.config.ts
import remarkDirective from 'remark-directive';
import { defineDocumentType, makeSource } from 'contentlayer/source-files'
import readingTime from "reading-time";
import remarkGfm from 'remark-gfm'
import { h } from 'hastscript'
import { visit } from 'unist-util-visit'
import rehypeSlug from "rehype-slug";
// @ts-ignore
import rehypeFigure from "rehype-figure"
import GithubSlugger from 'github-slugger'
import { getGitFileUpdateTimestamp, getGitFileCreateTimestamp } from './app/utils/getGitTimeStamp';
import rehypePrettyCode from "rehype-pretty-code";
import { siteConfig } from './site.config';
import remarkMath from 'remark-math'

const slugger = new GithubSlugger()

function myRemarkPlugin() {
    /**
     * @param {import('mdast').Root} tree
     *   Tree.
     * @returns {undefined}
     *   Nothing.
     */
    return function (tree) {
        visit(tree, function (node) {
            console.log(111, tree)
            console.log(222, node)
            if (
                node.type === 'containerDirective' ||
                node.type === 'leafDirective' ||
                node.type === 'textDirective'
            ) {
                const data = node.data || (node.data = {})
                const hast = h(node.name, node.attributes || {})

                data.hName = hast.tagName
                data.hProperties = hast.properties
            }
        })
    }
}

const computedFields: import('contentlayer/source-files').ComputedFields = {
    urlslug: {
        type: "string",
        resolve: (doc) => `/${doc._raw.flattenedPath}`,
    },
    slug: {
        type: "string",
        resolve: (doc) => `/${doc._raw.flattenedPath}`.toLowerCase(),
    },
    createTime: {
        type: 'number',
        resolve: async (doc) => {
            const createTime = await getGitFileCreateTimestamp(doc._raw.sourceFilePath);
            return createTime;
        },
    },
    updateTime: {
        type: 'number',
        resolve: async (doc) => {
            const updateTime = await getGitFileUpdateTimestamp(doc._raw.sourceFilePath);
            return updateTime;
        },
    },
    slugAsParams: {
        type: "string",
        resolve: (doc) =>
            doc._raw.flattenedPath.split("/").slice(1).join("/").toLowerCase(),
    },
    readingTime: {
        type: "json",
        resolve: (doc) => readingTime(doc.body.raw, { wordsPerMinute: 500 }),
    },
    headings: {
        type: "json",
        resolve: async (doc) => {
            const regXHeader = /\n(?<flag>#{2,6})\s+(?<content>.+)/g;
            const headings = Array.from(doc.body.raw.matchAll(regXHeader)).map(
                (item: any) => {
                    const flag = item.groups?.flag;
                    const content = item.groups?.content;
                    return {
                        level:
                            flag?.length == 1 ? "one" : flag?.length == 2 ? "two" : "three",
                        text: content,
                        id: slugger.slug(content),
                    };
                }
            );
            return headings;
        },
    },
};


export const Post = defineDocumentType(() => ({
    name: 'Post',
    filePathPattern: `post/**/*.mdx`,
    contentType: "mdx",
    fields: {
        title: { type: 'string', required: false },
        description: { type: "string", required: false },
        image: { type: 'string', required: false },
        tags: {
            type: "list",
            default: [],
            of: { type: "string" },
        },
    },
    computedFields
}))

export const Page = defineDocumentType(() => ({
    name: 'Page',
    filePathPattern: `page/**/*.mdx`,
    contentType: "mdx",
    fields: {
        title: { type: 'string', required: false },
        image: { type: 'string', required: false },
        description: { type: 'string', required: false }
    },
    computedFields
}))

const options: import('rehype-pretty-code').Options = {
    theme: "github-dark-dimmed",
    keepBackground: true
};

export default makeSource({
    contentDirPath: siteConfig.docPath,
    documentTypes: [Post, Page],
    mdx: {
        remarkPlugins: [remarkGfm, remarkMath, remarkDirective, myRemarkPlugin],
        rehypePlugins: [
            // @ts-ignore
            [rehypePrettyCode, options],
            rehypeFigure,
            rehypeSlug,
        ],
    }
})
```

# Error

```
Error: Found 1 problems in 6 documents.

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.
     
     • "post/china.mdx": UnexpectedMDXError: Error: Build failed with 1 error:
     _mdx_bundler_entry_point-9eec5d12-299b-4628-8552-df71eb9006e8.mdx:0:0: ERROR: [plugin: @mdx-js/esbuild] TypeError: Cannot set properties of undefined (setting 'directiveAttributes')
         at Object.enterAttributes (file:///Users/kinda/Developer/blog/kinda.info/node_modules/mdast-util-directive/lib/index.js:186:33)
         at compile (file:///Users/kinda/Developer/blog/kinda.info/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
         at fromMarkdown (file:///Users/kinda/Developer/blog/kinda.info/node_modules/mdast-util-from-markdown/lib/index.js:187:29)
         at parser (file:///Users/kinda/Developer/blog/kinda.info/node_modules/remark-parse/lib/index.js:18:12)
         at Function.parse (file:///Users/kinda/Developer/blog/kinda.info/node_modules/@mdx-js/mdx/node_modules/unified/lib/index.js:273:12)
         at executor (file:///Users/kinda/Developer/blog/kinda.info/node_modules/@mdx-js/mdx/node_modules/unified/lib/index.js:393:31)
         at new Promise (<anonymous>)
         at Function.process (file:///Users/kinda/Developer/blog/kinda.info/node_modules/@mdx-js/mdx/node_modules/unified/lib/index.js:380:14)
         at process (file:///Users/kinda/Developer/blog/kinda.info/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:50:22)
         at onload (file:///Users/kinda/Developer/blog/kinda.info/node_modules/@mdx-js/esbuild/lib/index.js:151:22)
         at requestCallbacks.on-load (/Users/kinda/Developer/blog/kinda.info/node_modules/esbuild/lib/main.js:1434:28)
         at processTicksAndRejections (node:internal/process/task_queues:95:5)
         at handleRequest (/Users/kinda/Developer/blog/kinda.info/node_modules/esbuild/lib/main.js:729:13)
     

SourceFetchDataError: {
  "_tag": "HandledFetchDataError"
}
```

**Comment by connorwforsyth** [comment]
I was running into a similar issue for remarkGfm and installed these versions of contentlayer and remark-gfm which fixed the issue:

```
---
"dependencies": {
    "remark-gfm": "^3.0.1",
    "contentlayer": "^0.3.1",
    "next-contentlayer": "^0.3.1",
---
  ```

**Comment by Alndaly** [comment]
```json
...
"dependencies": {
    "@giscus/react": "^2.4.0",
    "@headlessui/react": "^1.7.18",
    "@heroicons/react": "^2.1.1",
    "@mdx-js/loader": "^3.0.0",
    "@mdx-js/react": "^3.0.0",
    "@microflash/remark-callout-directives": "^2.0.0",
    "@next/mdx": "^14.0.4",
    "@tailwindcss/typography": "^0.5.10",
    "@types/fs-extra": "^11.0.4",
    "@types/mdx": "^2.0.10",
    "@vercel/analytics": "^1.1.2",
    "@vercel/speed-insights": "^1.0.7",
    "ahooks": "^3.7.8",
    "classnames": "^2.5.1",
    "contentlayer": "^0.3.4",
    "fs-extra": "^11.2.0",
    "fuse.js": "^7.0.0",
    "github-slugger": "^2.0.0",
    "gray-matter": "^4.0.3",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "moment-timezone": "^0.5.44",
    "next": "14.0.4",
    "next-contentlayer": "^0.3.4",
    "next-mdx-remote": "^4.4.1",
    "next-themes": "^0.2.1",
    "nextjs-toploader": "^1.6.6",
    "react": "^18",
    "react-dom": "^18",
    "reading-time": "^1.5.0",
    "rehype-figure": "^1.0.1",
    "rehype-highlight": "^7.0.0",
    "rehype-katex": "^7.0.0",
    "rehype-pretty-code": "^0.12.6",
    "rehype-shikiji": "^0.10.0-beta.8",
    "rehype-slug": "^6.0.0",
    "remark-directive": "^3.0.0",
    "remark-gfm": "3.0.1",
    "remark-math": "^6.0.0",
    "rss": "^1.2.2",
    "shikiji": "^0.9.0",
    "to-vfile": "^8.0.0",
    "unified": "^11.0.4"
  },
  "devDependencies": {
    "@types/cross-spawn": "^6.0.6",
    "@types/lodash": "^4.14.202",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@types/rss": "^0.0.32",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.4",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
...
```

This is my package.json, I've included all three packages, but it still doesn't work. However, I've managed to bypass the issue by manually invoking unified, although it's not quite logical, it works in practice.
