### ISSUE TITLE
Error when running npm run dev with next 13 and Contentlayer

### ISSUE THREAD

**Issue by art321995** [contentlayerdev/contentlayer#655]
Error when running npm run dev with next 13 and Contentlayer

"next": "14.1.4"
"next-contentlayer": "^0.3.4"

Error:

PS C:\Users\H378136\Documents\Index\React\react-next13\03-blog-next-mdx> npm run dev

> 03-blog-next-mdx@0.1.0 dev
> next dev

file:///C:/Users/H378136/Documents/Index/React/react-next13/03-blog-next-mdx/next.config.mjs:1
const { withContentlayer } = require("next-contentlayer");
                             ^

ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///C:/Users/H378136/Documents/Index/React/react-next13/03-blog-next-mdx/next.config.mjs:1:30
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadConfig (C:\Users\H378136\Documents\Index\React\react-next13\03-blog-next-mdx\node_modules\next\dist\server\config.js:696:36)
    at async nextDev (C:\Users\H378136\Documents\Index\React\react-next13\03-blog-next-mdx\node_modules\next\dist\cli\next-dev.js:197:14)
    at async main (C:\Users\H378136\Documents\Index\React\react-next13\03-blog-next-mdx\node_modules\next\dist\bin\next:155:5)

Node.js v21.7.1

**Comment by davidsonaguiar** [comment]
if you use import and export instead of require and module.export it works

---> ReferenceError: require is not defined in ES module scope, you can use import instead
