### ISSUE TITLE
esbuild.context is not a function

### ISSUE THREAD

**Issue by rikusen0335** [contentlayerdev/contentlayer#662]
```
pnpm dev

> @ dev /Users/soshi/workspace/ReLog
> PORT=3112 next dev

This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

An unchecked error was produced.

TypeError: esbuild.context is not a function
    at T.tryCatchPromise.UnknownEsbuildError.error.error (file:///Users/soshi/workspace/ReLog/node_modules/.pnpm/@contentlayer+core@0.3.4_esbuild@0.13.15/node_modules/@contentlayer/core/dist/getConfig/esbuild.js:64:79)
    at file:///Users/soshi/workspace/ReLog/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Effect/promise.mjs:13:5
    at file:///Users/soshi/workspace/ReLog/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Effect/effectAsync.mjs:30:5
    at FiberContext.evaluateNow (file:///Users/soshi/workspace/ReLog/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:892:35)
    at file:///Users/soshi/workspace/ReLog/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Fiber/context.mjs:504:33
    at file:///Users/soshi/workspace/ReLog/node_modules/.pnpm/@effect-ts+system@0.57.5/node_modules/@effect-ts/system/_mjs/Support/Scheduler/index.mjs:11:22

Fiber: #5 (started at: 2024-06-20T02:19:31.155Z) was supposed to continue to: <empty trace>
```

**Comment by rikusen0335** [comment]
Idk why is this happen but removing `remark-mdx-code-meta` `remark-mdx-images` `unist-util-visit` `hastscript` `gray-matter` and upgrading `puppeteer` guided me to fix.
