### ISSUE TITLE
Contentful errors file missing

### ISSUE THREAD

**Issue by seancdavis** [contentlayerdev/contentlayer#72]
I did the following:

```
npm install contentlayer @contentlayer/source-contentful
```

Then set env vars and a config file:

```ts
import { makeSourcePlugin } from "@contentlayer/source-contentful";

export default makeSourcePlugin({
  accessToken: process.env["CONTENTFUL_ACCESS_TOKEN"]!,
  spaceId: process.env["CONTENTFUL_SPACE_ID"]!,
  environmentId: process.env["CONTENTFUL_ENV"]!,
});
```

And ran a build. Saw the following:

```
ConfigReadError {
  error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/project/node_modules/@contentlayer/source-contentful/dist/errors' imported from /path/to/project/node_modules/@contentlayer/source-contentful/dist/contentful.js
      at finalizeResolution (internal/modules/esm/resolve.js:276:11)
      at moduleResolve (internal/modules/esm/resolve.js:699:10)
      at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
      at Loader.resolve (internal/modules/esm/loader.js:88:40)
      at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
      at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
      at link (internal/modules/esm/module_job.js:55:36) {
    code: 'ERR_MODULE_NOT_FOUND'
  },
  configPath: '/path/to/project/contentlayer.config.ts',
  _tag: 'ConfigReadError',
  toString: [Function (anonymous)]
}
```

**Comment by schickling** [comment]
Will be released with the next upcoming version.
