### ISSUE TITLE
Contentlayer stuck with following stacktrace.

### ISSUE THREAD

**Issue by marcofranssen** [contentlayerdev/contentlayer#80]
Catching following stacktrace since adding the following to my script.

```js
const experienceFields = {
  position: { type: "string", required: true },
  url: { type: "string", required: true },
  startDate: { type: "date", required: true },
  endDate: { type: "date", required: false },
  summary: { type: "string", required: true },
  hightlights: { type: "list", of: { type: "string" }, required: false },
}

const WorkExperience = defineNestedType(() => ({
  name: "WorkExperience",
  fields: {
    company: { type: "string", required: true },
    ...experienceFields,
  },
}));

const VolunteerExperience = defineNestedType(() => ({
  name: "VolunteerExperience",
  fields: {
    organization: { type: "string", required: true },
    ...experienceFields,
  },
}));
```

Even after reverting the destructure approach to normal contentlayer continues to be in this error state. See here the full code.

<details>
  <summary>resume.js</summary>

```js
import {
  defineDocumentType,
  defineNestedType,
} from "contentlayer/source-files";

export const Resume = defineDocumentType(() => ({
  name: "Resume",
  filePathPattern: "resume.json",
  bodyType: "none",
  isSingleton: true,
  fields: {
    basics: { type: "nested", of: ResumeBasics, required: true },
    work: { type: "list", of: WorkExperience, required: true },
    volunteer: { type: "list", of: VolunteerExperience, required: true },
    education: { type: "list", of: Education, required: true },
    awards: { type: "list", of: { type: "string" }, required: false },
    publications: { type: "list", of: { type: "string" }, required: false },
    skills: { type: "list", of: Skill, required: false },
    languages: { type: "list", of: Language, required: false },
    interests: { type: "list", of: Interest, required: false },
    references: { type: "list", of: { type: "string" }, required: false },
  },
}));

const ResumeBasics = defineNestedType(() => ({
  name: "Basics",
  fields: {
    name: { type: "string", required: true },
    label: { type: "string", required: true },
    picture: { type: "string", required: true },
    email: { type: "string", required: true },
    phone: { type: "string", required: true },
    url: { type: "string", required: true },
    summary: { type: "string", required: true },
    location: { type: "nested", of: ResumeLocation, required: false },
    profiles: { type: "list", of: ResumeProfile, required: false },
  },
}));

const ResumeLocation = defineNestedType(() => ({
  name: "Location",
  fields: {
    address: { type: "string", required: true },
    postalCode: { type: "string", required: true },
    city: { type: "string", required: true },
    countryCode: { type: "string", required: true },
    region: { type: "string", required: true },
  },
}));

const ResumeProfile = defineNestedType(() => ({
  name: "Profile",
  fields: {
    network: { type: "string", required: true },
    username: { type: "string", required: true },
    url: { type: "string", required: true },
  },
}));

const experienceFields = {
  position: { type: "string", required: true },
  url: { type: "string", required: true },
  startDate: { type: "date", required: true },
  endDate: { type: "date", required: false },
  summary: { type: "string", required: true },
  hightlights: { type: "list", of: { type: "string" }, required: false },
}

const WorkExperience = defineNestedType(() => ({
  name: "WorkExperience",
  fields: {
    company: { type: "string", required: true },
    position: { type: "string", required: true },
    url: { type: "string", required: true },
    startDate: { type: "date", required: true },
    endDate: { type: "date", required: false },
    summary: { type: "string", required: true },
    hightlights: { type: "list", of: { type: "string" }, required: false },
  },
}));

const VolunteerExperience = defineNestedType(() => ({
  name: "VolunteerExperience",
  fields: {
    organization: { type: "string", required: true },
    position: { type: "string", required: true },
    url: { type: "string", required: true },
    startDate: { type: "date", required: true },
    endDate: { type: "date", required: false },
    summary: { type: "string", required: true },
    hightlights: { type: "list", of: { type: "string" }, required: false },
  },
}));

const Education = defineNestedType(() => ({
  name: "Education",
  fields: {
    institution: { type: "string", required: true },
    url: {type:"string"}, required: false},
    area: { type: "string", required: true },
    studyType: { type: "string", required: true },
    startDate: { type: "date", required: true },
    endDate: { type: "date", required: false },
    score: { type: "string", required: true },
    courses: { type: "list", of: { type: "string" }, required: false },
  },
));

const Skill = defineNestedType(() => ({
  name: "Skill",
  fields: {
    name: { type: "string", required: true },
    level: { type: "string", required: true },
    keywords: { type: "list", of: { type: "string" }, required: false },
  },
}));

const Language = defineNestedType(() => ({
  name: "Language",
  fields: {
    language: { type: "string", required: true },
    fluency: { type: "string", required: true },
  },
}));

const Interest = defineNestedType(() => ({
  name: "Interest",
  fields: {
    name: { type: "string", required: true },
    keywords: { type: "list", of: { type: "string" }, required: false },
  },
}));
```

</details>

<details>
  <summary>Log</summary>

```shell
$ node_modules/.bin/contentlayer build --clearCache --verbose

Cache cleared successfully
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #1.
║  ║  ║ 
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║ 
║  ║ Error: A case was not handled for value: false
║  ║     at Module.casesHandled (file:///Users/marco/code/priv/nextjs-blog/node_modules/@contentlayer/utils/src/index.ts:62:9)
║  ║     at traverseField (file:///Users/marco/code/priv/nextjs-blog/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:290:15)
║  ║     at Array.forEach (<anonymous>)
║  ║     at traverseNestedDef (file:///Users/marco/code/priv/nextjs-blog/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:249:41)
║  ║     at traverseListFieldItem (file:///Users/marco/code/priv/nextjs-blog/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:301:16)
║  ║     at traverseField (file:///Users/marco/code/priv/nextjs-blog/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:274:16)
║  ║     at Array.forEach (<anonymous>)
║  ║     at collectNestedDefs (file:///Users/marco/code/priv/nextjs-blog/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:305:60)
║  ║     at file:///Users/marco/code/priv/nextjs-blog/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:74:24
║  ║     at Generator.next (<anonymous>)
║  ║ 
║  ║ Fiber: #9 (started at: 2021-12-28T16:05:04.461Z) was supposed to continue to:
║  ║ 
║  ║   a future continuation at packages/@contentlayer/source-files/src/index.ts:54:17
║  ║ 
║  ║ Fiber: #9 (started at: 2021-12-28T16:05:04.461Z) Execution trace:
║  ║ 
║  ║   packages/@contentlayer/source-files/src/schema/provideSchema.ts:17:8
║  ║ 
║  ║ Fiber: #9 (started at: 2021-12-28T16:05:04.461Z) was spawned by:
║  ║ 
║  ║ Fiber: #1 (started at: 2021-12-28T16:05:03.709Z) was supposed to continue to:
║  ║ 
║  ║   a future continuation at packages/@contentlayer/core/src/generation/generate-dotpkg.ts:78:13
║  ║ 
║  ║ Fiber: #1 (started at: 2021-12-28T16:05:03.709Z) Execution trace:
║  ║ 
║  ║   packages/@contentlayer/core/src/generation/generate-dotpkg.ts:74:16
║  ║   packages/@contentlayer/cli/src/commands/BuildCommand.ts:24:12
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:36:18
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:35:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:43:15
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:35:26
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:33:12
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:113:12
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:71:36
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:163:13
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:154:26
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:153:30
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:143:26
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:142:31
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:131:26
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:130:15
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:116:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:114:12
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:117:14
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:66:15
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:65:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:64:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:47:22
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:72:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:71:12
║  ║ 
║  ║ Fiber: #1 (started at: 2021-12-28T16:05:03.709Z) was spawned by: <empty trace>
║  ▼
▼

OS: darwin 21.1.0 (arch: x64)
Process: /usr/local/Cellar/node@16/16.13.1/libexec/node /Users/marco/code/priv/nextjs-blog/node_modules/.bin/contentlayer build --clearCache --verbose
Node version: v16.13.1
Contentlayer version: 0.0.33
```

</details>

**Comment by marcofranssen** [comment]
Eventually found the issue by reapplying all definitions one by one. 

Reason for the Stacktrace was in the education definition.

```js
    url: {type:"string"}, required: false},
```

which should have been

```js
    url: { type:"string", required: false },
```

Somehow my IDEA was not highlighting this error. 🤕
