### ISSUE TITLE
Example for list type in docs does not work

### ISSUE THREAD

**Issue by timlrx** [contentlayerdev/contentlayer#96]
The documentation for list over [here](https://www.contentlayer.dev/docs/reference/local-source/field-types) seems to be wrong / outdated. From the typescript output, it seems to require an addition field `of` so the correct example should look like:

```
defineDocumentType(() => ({
  // ...
  fields: {
    tags: {
      type: 'list',
      of: { type: 'string' }
    },
  },
}))
```

**Comment by schickling** [comment]
@seancdavis can you take a look at this? :)

**Comment by wiktor-jurek** [comment]
Thanks for this! Saved my bacon 😁! Without giving the 'of' property, I got this stacktrace:

```
Contentlayer config change detected. Updating type definitions and data...
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #282.
║  ║  ║
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║
║  ║ TypeError: Cannot read properties of undefined (reading 'type')
║  ║     at fieldListItemsToCoreFieldListDefItems (file:///home/wiktor/Development-Linux/workspacemodels/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:249:28)
║  ║     at fieldDefEntryToCoreFieldDef (file:///home/wiktor/Development-Linux/workspacemodels/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:157:13)
║  ║     at file:///home/wiktor/Development-Linux/workspacemodels/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:25:9        
║  ║     at Array.map (<anonymous>)
║  ║     at next (file:///home/wiktor/Development-Linux/workspacemodels/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:24:64)
║  ║     at Generator.next (<anonymous>)
║  ║     at ISuspend.factory (file:///home/wiktor/Development-Linux/workspacemodels/node_modules/@effect-ts/system/_src/Effect/gen.ts:135:28)     
║  ║     at FiberContext.evaluateNow (file:///home/wiktor/Development-Linux/workspacemodels/node_modules/@effect-ts/system/_src/Fiber/context.ts:1173:51)
║  ║     at file:///home/wiktor/Development-Linux/workspacemodels/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
║  ║     at file:///home/wiktor/Development-Linux/workspacemodels/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9
║  ║
║  ║ Fiber: #284 (started at: 2022-03-27T21:27:35.564Z) was supposed to continue to:
║  ║
║  ║   a future continuation at packages/@contentlayer/source-files/src/index.ts:54:17
║  ║
║  ║ Fiber: #284 (started at: 2022-03-27T21:27:35.564Z) Execution trace:
║  ║
║  ║   packages/@contentlayer/source-files/src/schema/provideSchema.ts:17:8
║  ║
║  ║ Fiber: #284 (started at: 2022-03-27T21:27:35.564Z) was spawned by:
║  ║
║  ║ Fiber: #282 (started at: 2022-03-27T21:27:35.564Z) was supposed to continue to:
║  ║
║  ║   a future continuation at packages/@contentlayer/core/src/generation/generate-dotpkg.ts:79:13
║  ║
║  ║ Fiber: #282 (started at: 2022-03-27T21:27:35.564Z) Execution trace:
║  ║
║  ║   packages/@contentlayer/core/src/generation/generate-dotpkg.ts:75:16
║  ║
║  ║ Fiber: #282 (started at: 2022-03-27T21:27:35.564Z) was spawned by:
║  ║
║  ║ Fiber: #280 (started at: 2022-03-27T21:27:35.563Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #280 (started at: 2022-03-27T21:27:35.563Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #280 (started at: 2022-03-27T21:27:35.563Z) was spawned by:
║  ║
║  ║ Fiber: #277 (started at: 2022-03-27T21:27:35.549Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #277 (started at: 2022-03-27T21:27:35.549Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #277 (started at: 2022-03-27T21:27:35.549Z) was spawned by:
║  ║
║  ║ Fiber: #3 (started at: 2022-03-27T21:07:52.951Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #3 (started at: 2022-03-27T21:07:52.951Z) Execution trace:
║  ║
║  ║   packages/@contentlayer/utils/src/effect/ConsoleService.ts:9:18
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:163:13
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:154:26
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:153:30
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:143:26
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:142:31
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:131:26
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:130:15
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:116:10
║  ║   packages/@contentlayer/utils/src/effect/Stream.ts:32:83
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:163:13
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:154:26
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:153:30
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:143:26
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:142:31
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:131:26
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:130:15
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:116:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:118:12
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:121:14
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:70:15
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:69:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:68:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:51:22
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:76:10
║  ║
║  ║ Fiber: #3 (started at: 2022-03-27T21:07:52.951Z) was spawned by:
║  ║
║  ║ Fiber: #0 (started at: 2022-03-27T21:07:52.939Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #0 (started at: 2022-03-27T21:07:52.939Z) Execution trace:
║  ║
║  ║   packages/@contentlayer/utils/src/tracing-effect/index.ts:45:45
║  ║   packages/@contentlayer/core/src/cwd.ts:22:49
║  ║   packages/@contentlayer/core/src/cwd.ts:9:18
║  ║   packages/@contentlayer/core/src/cwd.ts:8:23
║  ║   packages/@contentlayer/core/src/cwd.ts:7:29
║  ║   packages/@contentlayer/core/src/runMain.ts:23:32
║  ║   packages/@contentlayer/core/src/runMain.ts:14:12
║  ║
║  ║ Fiber: #0 (started at: 2022-03-27T21:07:52.939Z) was spawned by: <empty trace>
║  ▼
▼
```

**Comment by seancdavis** [comment]
Thanks for bringing this up, @timlrx! I moved to contentlayerdev/website#47 and will look into it next week.
